neo4j/apoc

- common/src/main/java/apoc/util/Util.java
- core/src/test/java/apoc/util/UtilTest.java
SHOW DATABASES has a couple of breaking changes in 5.x
* role is now simply 'primary' or 'secondary'
* writer is used to determine the leader
> Adapt to breaking changes to SHOW DATABASES

- build.gradle
Fixes "./gradlew versions" task
> Fix "./gradlew versions" task

- build.gradle
- readme.adoc
We've moved on to 5.1.0 in neo4j, this should fix failing CI jobs
> Bumps version of neo4j

- core/src/main/java/apoc/periodic/Periodic.java
- core/src/main/java/apoc/refactor/rename/Rename.java
Fixes #18
Changed 50 with number of processors available
> Fixes #18: Default parallel concurrency of 50 is too high

- common/src/test/resources/spatial.json
- core/src/main/java/apoc/spatial/Geocode.java
- core/src/test/java/apoc/spatial/GeocodeTest.java
- core/src/test/java/apoc/spatial/SpatialTest.java
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/95a40fd0aa4da6b1ce953860ba12256b889ac2c6
> Fixes #2739: Allow apoc.spatial.geoCodeOnce to also receive config via procedure call (#2832)

- core/src/main/java/apoc/cypher/CypherInitializer.java
- core/src/main/java/apoc/meta/Meta.java
- core/src/test/java/apoc/meta/MetaTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/985463e5812f8e35fe1991c1d96f72b433593daa
> `apoc.meta.relTypeProperties` doest not return relationship information (#2935)

- build.gradle
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
Related to [#3169](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3169)
> Add core repo as a git submodule in extended

- readme.adoc
Let users know where the extended repo is and have the matrix show 5.1
> [uGTIvlKp] Add link to extended and update readme matrix

- common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
- common/src/test/java/apoc/util/UtilIT.java
- core/src/main/java/apoc/export/cypher/ExportCypher.java
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
- core/src/test/java/apoc/load/LoadJsonTest.java
To think about: do we want to backport these fixes to 4.x?
> [4Bmcyc2U] Fix and enable some ignored tests

- core/src/test/java/apoc/refactor/rename/RenameTest.java
Try fixing flaky testDeadlockException
Added more `SIMILAR_TO` relationships to significantly increase the probability of deadlock.
Indeed, there may be a very small probability that the test will fail, 
but I don't think there are any other solutions (apart from introducing a retry mechanism)
> [4Bmcyc2U] Try fixing flaky testDeadlockException

- readme.adoc
[2vc7QKMx] Update the env to not use the old way for adding env to APOC
> Update Docker env help

- core/src/main/java/apoc/algo/PathFinding.java
- core/src/main/java/apoc/coll/Coll.java
- core/src/main/java/apoc/diff/Diff.java
- core/src/main/java/apoc/export/arrow/ExportArrow.java
- core/src/main/java/apoc/load/LoadArrow.java
- core/src/main/java/apoc/nodes/Grouping.java
- core/src/main/java/apoc/nodes/Nodes.java
- core/src/main/java/apoc/stats/DegreeDistribution.java
- core/src/main/java/apoc/text/Strings.java
- core/src/test/java/apoc/help/HelpTest.java
Update missed and malformed descriptions
> [vULR7sSU] Update APOC descriptions

- common/src/main/java/apoc/ApocConfig.java
- common/src/main/java/apoc/util/FileUtils.java
- common/src/main/java/apoc/util/Util.java
- common/src/test/java/apoc/util/UtilIT.java
- core/src/main/java/apoc/load/Xml.java
- core/src/test/java/apoc/load/XmlTest.java
Also fixes ignored test for URL to file redirect.
Co-authored-by: louise <louise.soderstrom@neo4j.com>
> [eOxJMLMv] Checks redirects for blocked IPs instead of just final location.

- common/src/main/java/apoc/meta/Types.java
- core/src/main/java/apoc/export/json/JsonFormat.java
- core/src/test/java/apoc/export/json/ExportJsonTest.java
Fixes issue where a class cast exception stopped arrays of primitive values from serializing to JSON.
Also did some general code cleanup as I went 🧹
> [3KXXQazJ] Fix bug with serializing arrays of primitive values for json export query

- core/src/test/java/apoc/meta/MetaTest.java
- core/src/test/java/apoc/schema/SchemasTest.java
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
The relationship uniqueness constraints are now turned on by default in Neo dev (feature flag set to true)
> [FmCGhDLD] Remove relationship constraint feature flag

- common/src/main/java/apoc/meta/MetaConfig.java
- common/src/main/java/apoc/meta/Tables4LabelsProfile.java
- core/src/main/java/apoc/load/SkipWhitespaceInputStream.java
- core/src/main/java/apoc/path/LabelMatcherGroup.java
- core/src/main/java/apoc/path/LabelSequenceEvaluator.java
- core/src/main/java/apoc/path/NodeEvaluators.java
- core/src/main/java/apoc/path/PathExplorer.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTestUtil.java
- core/src/test/java/apoc/path/ExpandPathTest.java
- core/src/test/java/apoc/path/LabelSequenceTest.java
- core/src/test/java/apoc/path/NodeFilterTest.java
- core/src/test/java/apoc/path/SubgraphTest.java
- core/src/test/java/apoc/refactor/CloneSubgraphTest.java
Add config values for allowlist and denylist and tests and deprecate the use of Whitelist and Blacklist.
> [RhUZ6yD8] Renaming for allowlist and denylist

- core/src/main/java/apoc/coll/Coll.java
e.g
`RETURN apoc.coll.different([1,2,3])` Returns true
`RETURN apoc.coll.different([1,1,3])` Returns false
> [zsiiACOA] Update the apoc.coll.different description to accurately describe the function

- core/src/test/java/apoc/meta/MetaTest.java
- core/src/test/java/apoc/schema/SchemasTest.java
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
Reverts neo4j/apoc#270
Needs to go in after the feature flag is re-applied in Neo4j
> [NOID] Revert "Remove relationship constraint feature flag"

- test-utils/src/main/java/apoc/util/TestcontainersCausalCluster.java
Fixed wrong password in cluster test's getDriver() after [this change](https://github.com/neo4j/apoc/commit/a8d880dd7aad278adf17763902bbb331a718777e)
> [NOID] Fix getDriver() password in cluster test

- readme.adoc
Same content changes as for APOC docs: https://github.com/neo4j/docs-apoc/pull/86
> [UDzPn3dS] Update readme about loading and unrestricting

- build.gradle
- readme.adoc
Bump version after the release of 5.4
> [NOID] Bump version to 5.5.0

- core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
Cherry-pick from 4.4: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3393/commits/614ef7bcd9b43ea1e6e807c43dfe0b2ebf797ed1
> [gRNAet7B] Changed AtomicReference with 1-elem array

- test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
Revert change to support Neo4j 5.4 release candidate.
> Revert 273 5.x begin transaction

- build.gradle
- readme.adoc
> [FPaRo3uM] Bump version 5.4.1

- core/src/main/java/apoc/trigger/TriggerNewProcedures.java
Changed trigger descriptions to be consistent with docs pr: https://github.com/neo4j/docs-apoc/pull/83
> [gRNAet7B] Changed trigger descriptions

- core/src/test/java/apoc/meta/MetaTest.java
- core/src/test/java/apoc/nodes/GroupingTest.java
Cherry pick (core part) https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/be1088a7e247ded3a3f4af02e46e2a22c3b2ca17
> [NOID] Added var. adoc and test for meta configs (neo4j-contrib/neo4j-apoc-procedures#3032)

- core/src/main/java/apoc/trigger/TriggerNewProcedures.java
[mcub3FQf] Improve triggers error messages
> [mcub3FQf] Improve triggers error messages

- readme.adoc
Update to latest 4.4.x (and fix typo) and add newer 5.x releases
> [NOID] Update version matrix

- common/src/main/java/apoc/meta/MetaConfig.java
- common/src/main/java/apoc/meta/SampleMetaConfig.java
- common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
- core/src/main/java/apoc/meta/Meta.java
- core/src/test/java/apoc/meta/MetaTest.java
APOC docs [here](https://github.com/neo4j/docs-apoc/pull/104). 
Make sampling start working as intended. Clean up a little bit how it all works and add tests.
> [04b6IYYB] improve performance of apoc.meta procedures

- common/src/main/java/apoc/util/FileUtils.java
Fixes some broken links in apoc
> [NOID] Updates broken links

- core/build.gradle
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
- it/build.gradle
- it/src/test/java/apoc/it/core/ExportCsvS3Test.java
- it/src/test/java/apoc/it/core/ExportCypherS3Test.java
- it/src/test/java/apoc/it/core/ExportGraphMLS3Test.java
- it/src/test/java/apoc/it/core/ExportJsonS3Test.java
Because they seem to be flaky as well, they depend on an S3 container, so it's better to have them in the integration tests package.
> [F61iNGQX] Moves S3 tests to integration tests package

- core/build.gradle
- core/src/test/java/apoc/atomic/AtomicTest.java
- core/src/test/java/apoc/convert/ConvertJsonTest.java
- core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
- core/src/test/java/apoc/export/json/ImportJsonTest.java
- core/src/test/java/apoc/graph/GraphsTest.java
- core/src/test/java/apoc/load/LoadJsonTest.java
- core/src/test/java/apoc/load/XmlTest.java
- core/src/test/java/apoc/path/SubgraphTest.java
- core/src/test/java/apoc/periodic/PeriodicTest.java
Remove dependency as it also had some vulnerabilities and last update for this library was 2016! (update transitive dependencies to use correct imports as well)
> [NOID] Remove unused cassandra test dependency

- core/src/test/java/apoc/periodic/PeriodicTest.java
Follow-up on #352, which has not gone far enough.
> [NOID] Lenient periodic test

- core/src/main/java/apoc/export/csv/CsvEntityLoader.java
- core/src/main/java/apoc/export/csv/ImportCsv.java
- core/src/main/java/apoc/refactor/GraphRefactoring.java
- core/src/test/java/apoc/cypher/CypherTest.java
- core/src/test/java/apoc/export/BigGraphTest.java
- core/src/test/java/apoc/export/csv/ImportCsvTest.java
- core/src/test/java/apoc/export/json/ImportJsonTest.java
- core/src/test/java/apoc/load/LoadJsonTest.java
- core/src/test/java/apoc/load/XmlTest.java
- test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
- test-utils/src/main/java/apoc/util/TransactionTestUtil.java
> [NOID] REVERT - Fixed testImportCsvTerminate and added TerminationGuard to apoc.import.csv 

- core/src/main/java/apoc/export/cypher/ExportCypher.java
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Forced `stream` and `streamStatements` to `"false"`
> [ivaiMqVb] CALL apoc.export.cypher.schema(null, { stream: true }) returns nothing

- test-utils/src/main/java/apoc/util/s3/S3Container.java
Used in extended here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3295/files
> [NOID] restored S3Container.putFile()

- common/build.gradle
- core/build.gradle
- processor/build.gradle
- test-utils/build.gradle
Changed consistently with the neo4j one: https://github.com/neo4j/neo4j/blob/5.6/pom.xml#L33
> [nKMspF5h] Change developer tag in pom.xml

- core/src/test/java/apoc/spatial/GeocodeTest.java
See [here](https://github.com/neo4j/apoc/actions/runs/4756662593/jobs/8457852964#step:4:17759)
Retry if an error with message "connect timed out" is thrown
> [NOID] flaky timeout geocode test

- core/src/main/java/apoc/export/json/JsonImporter.java
- it/src/test/java/apoc/it/core/StartupTest.java
Cherry-picks https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3546
> [Fb3ZFQbn] Adds cypher initializer test

- core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
- core/src/test/java/apoc/trigger/TriggerRestartTest.java
Cherry-pick (core part) - https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/f4e977098ec26cca26efbc5d6d738c45d40d2269
> [NOID] Fix flaky ConfigTest (neo4j-contrib/neo4j-apoc-procedures#3559)

- it/src/test/java/apoc/it/core/WarmupEnterpriseTest.java
Changed `freki` with another supported database format
> [nmiayBrI] Fix WarmupEnterpriseTest.testWarmupIsntAllowedWithOtherStorageEngines

- LICENSES.txt
- NOTICE.txt
For some reason these weren't updated
> [NOID] Update testcontainers license dependencies

- LICENSES.txt
- NOTICE.txt
- common/build.gradle
- test-utils/build.gradle
Note: the comment to check javax.servlet.jsp:jsp-api:2.1 was done, and it hasn't updated so the comment stays for now
> [NOID] Snyk Hadoop updates

- LICENSES.txt
- NOTICE.txt
- core/build.gradle
Update Guava and consequent license files
> [NOID] Snyk Guava updates

- LICENSES.txt
- NOTICE.txt
> [NOID] Fix licenses

- test-utils/src/main/java/apoc/cypher/CypherTestUtil.java
The test is failing due to missing results, it might be that the actual procedure is broken instead, but not reproducible locally. I have added some debug statements to see if it will help us figure out what is happening.
Feel free to suggest another idea if you don't agree with this one :)
> [7BVOtcmX] Add debug statement to see if we can figure out cause of flaky test

- core/src/main/java/apoc/coll/Coll.java
- core/src/test/java/apoc/atomic/AtomicTest.java
- core/src/test/java/apoc/cypher/CypherTest.java
- core/src/test/java/apoc/export/BigGraphTest.java
- core/src/test/java/apoc/export/ImportAndLoadCoreSecurityTest.java
- core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
- core/src/test/java/apoc/export/csv/ImportCsvTest.java
- core/src/test/java/apoc/meta/MetaTest.java
- core/src/test/java/apoc/refactor/CloneSubgraphTest.java
- core/src/test/java/apoc/refactor/GraphRefactoringTest.java
- core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
- it/src/test/java/apoc/it/core/ExportCsvS3Test.java
- it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java
- it/src/test/java/apoc/it/core/ExportGraphMLS3Test.java
- it/src/test/java/apoc/it/core/ExportJsonS3Test.java
- it/src/test/java/apoc/it/core/ImportJsonEnterpriseFeaturesTest.java
I felt like cleaning up some of the thousands of warning in APOC, would be nice to slowly reduce this overtime :)
> [NOID] Some warning and deprecation clean up 🧹

- core/src/main/java/apoc/help/Help.java
- core/src/main/java/apoc/help/HelpResult.java
- core/src/test/java/apoc/help/HelpTest.java
Add isDeprecated now that SHOW FUNCTIONS also supports this.
> [Ko3jddbl] Add isDeprecated to apoc.help

- common/build.gradle
SNYK recommends we update this dependency
> [NOID] Update Google Cloud Storage dependency

- core/src/test/java/apoc/load/LoadJsonTest.java
- core/src/test/java/apoc/load/SimpleHttpHandler.java
- core/src/test/java/apoc/load/XmlTest.java
This was already approved, but the port number didn't play nice with TC so need to udpate that :)
> [YGQfavsP]  Dev fix flaky load tests

- LICENSES.txt
- NOTICE.txt
- core/build.gradle
- test-utils/build.gradle
Based on the Neo4j bump https://github.com/neo-technology/neo4j/pull/21987
> [NOID] Bump arrow versions

- build.gradle
Fixes for versions that have a minor greater than 9 :)
> Take into account minor versions that are larger than 9

- LICENSES.txt
- NOTICE.txt
- common/build.gradle
- core/build.gradle
linked to: https://github.com/neo-technology/neo4j/pull/22399
> [NoID] update dependencies according to neo4j bumps

- build.gradle
> [NOID] Upgrades testContainers dependency

- core/src/main/java/apoc/search/ParallelNodeSearch.java
`apoc.search.nodeAll` and `apoc.search.node` used to access a transaction from multiple threads.
> [jyX5Zi3L] Fix bug in apoc.search.nodeAll and apoc.search.node

- core/src/test/java/apoc/cypher/CypherTest.java
- test-utils/src/main/java/apoc/util/TransactionTestUtil.java
Relax test assertions around transaction timeout.
> [Bc2lkk3N] Fix flaky test

- core/src/test/java/apoc/cypher/CypherTest.java
> [h99LDu82] Fix flaky test

- it/src/test/java/apoc/it/common/UtilIT.java
I will review this test again, we need to get away from depending on core internals, but let's just fix the build for now.
> [NOID] Quick Fix UtilIT to fix build

- build.gradle
Add parameterized custom maven repository resource in build file.
> [NOID] Add parameterized custom maven repo resource in build file.

- LICENSES.txt
- NOTICE.txt
- common/build.gradle
Should go in together with https://github.com/neo-technology/neo4j/pull/23393
> [brxa3W4m] Adapt to Neo4j dependency bump

- build.gradle
Update neo4j docker override params in build.gradle, one param for each neo4j edition.
> [NOID] Update neo4j docker override params.

- it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
Attempt to fix flaky test assertion.
> [pgcq5tlP] Fix flaky test

- LICENSES.txt
- NOTICE.txt
- common/build.gradle
> [yaWCMgIP] Exclude asm to fix startup issue (#561)

- build.gradle
Update neo4j docker override params in build.gradle, one param for each neo4j edition. 
Cherry-picks #555
> [NOID] Update neo4j docker override params

- LICENSES.txt
- NOTICE.txt
- common/build.gradle
- it/build.gradle
- test-utils/build.gradle
> [NOID] Updates libraries suggested by Snyk

- core/src/main/java/apoc/convert/Json.java
- core/src/test/java/apoc/convert/ConvertJsonTest.java
Adds element id and rel element id to the tree, this allows us to check if a relationship-node pair is unique, before the assumption was that it was unique if the rel type and node id pair was unique, which meant nodes with 2 rels of the same type, pointing to the same node were ignored.
These extra fields are additive, which is why I think it is okay, let me know if you think this is breaking or not!
> [7nVhdJu3] apoc.convert.toTree keep all rels in tree fix

- LICENSES.txt
- NOTICE.txt
- core/build.gradle
This reverts commit 128db22099f09446e4dfaf8f7a9207d4d958da78.
> [NOID] Revert "[NOID] Bump arrow (#576)"

- LICENSES.txt
- NOTICE.txt
- core/build.gradle
- test-utils/build.gradle
Align arrow version with server.
> [NOID] Bump arrow

- LICENSES.txt
- NOTICE.txt
- build.gradle
- core/build.gradle
- test-utils/build.gradle
Align arrow and netty version with server.
> [NOID] Align arrow and netty version with server

- common/src/main/java/apoc/periodic/PeriodicUtils.java
- common/src/main/java/apoc/util/Util.java
- core/src/test/java/apoc/periodic/PeriodicTest.java
Make apoc.periodic.iterate rebind values before using them in inner transactions. Failing to do this can cause dead locks, failures and undefiened behaviour if the value contains nodes or relationships (because they carry transactions).
> [2oZpORer] Fix illegal use of inner transaction in apoc.periodic.iterate

- core/src/main/java/apoc/periodic/Periodic.java
- it/src/test/java/apoc/it/core/PeriodicIterateTest.java
- test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
Transfers the metadata of the outer transaction to the inner transactions of the periodic.iterate procedure.
> [olbYUBeG] Added meta-data to batches in periodic iterate

- core/src/test/java/apoc/export/BigGraphTest.java
- core/src/test/java/apoc/export/csv/ImportCsvTest.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
- core/src/test/java/apoc/load/LoadJsonTest.java
Talked with Misha who deprecated them, he said "please remove usage of that setting its not doing what people assume it was doing and in general case is harmful"
> [DBjU6j7r] Clean up deprecated settings

- common/src/main/java/apoc/util/FileUtils.java
- common/src/main/java/apoc/util/JsonUtil.java
- common/src/main/java/apoc/util/Util.java
- core/src/main/java/apoc/export/csv/CsvEntityLoader.java
- core/src/main/java/apoc/load/LoadArrow.java
- core/src/main/java/apoc/load/Xml.java
- core/src/test/java/apoc/spatial/SpatialTest.java
- it/src/test/java/apoc/it/core/RBACOnLoadTest.java
Added url check for loading files in APOC.
> [xHCYeCNX] Added UrlCheck for files

- common/src/main/java/apoc/export/util/ExportConfig.java
- common/src/main/java/apoc/export/util/FormatUtils.java
- core/src/main/java/apoc/export/csv/CsvFormat.java
- core/src/main/java/apoc/export/csv/CustomCSVWriter.java
- core/src/test/java/apoc/export/csv/ExportCsvTest.java
Update behaviour for how ifNeeded works as well as add new config for differentiating null values.
IfNeeded will now correctly quote strings e.g if a string has a quote in it, it will be quoted and escaped.
New config option: differentiateNullls which allows a user to have their null values differentiated from empty strings
Docs: https://github.com/neo4j/docs-apoc/pull/308
> [vMVMuOO7] Export CSV updates

- it/src/test/java/apoc/it/core/ExportCsvS3Test.java
Fixes broken CSV test - The TC build for PR checks was not running the tests correctly for our IT tests, so this test was actually broken in another PR even though that build was green :)
> [NOID] Fix broken APOC test

- core/src/main/java/apoc/convert/Json.java
- core/src/test/java/apoc/convert/PathsToJsonTreeTest.java
Return the root node as well as a single node is a path of 1.
Fixes issue: https://github.com/neo4j/apoc/issues/651
> [NOID] Return a node even if no relationships exist

- common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
- core/src/main/java/apoc/meta/Meta.java
- core/src/main/java/apoc/stats/DegreeDistribution.java
- core/src/main/java/apoc/stats/DegreeUtil.java
Testing to see if build passes here, since it didn't work in https://github.com/neo4j/apoc/pull/661.
> [NOID] Adapt to token constants updated location

- build.gradle
- readme.adoc
> [NOID] Bump to 5.26

- core/src/main/java/apoc/convert/Json.java
- core/src/main/java/apoc/create/Create.java
- core/src/main/java/apoc/export/arrow/ExportArrow.java
- core/src/main/java/apoc/load/LoadArrow.java
- core/src/main/java/apoc/load/LoadJson.java
- core/src/main/java/apoc/log/Neo4jLogStream.java
- core/src/main/java/apoc/map/Maps.java
- core/src/main/java/apoc/text/Strings.java
- core/src/main/java/apoc/trigger/Trigger.java
- core/src/main/java/apoc/warmup/Warmup.java
- core/src/test/resources/functions.json
- core/src/test/resources/procedures.json
- it/src/test/java/apoc/it/core/ApocVersionsTest.java
Some of these are removed for good, some are moving to APOC extended.
> [lYfZxdRz] Deprecate and remove procedures/functions for Cypher 25

- LICENSES.txt
- NOTICE.txt
- build.gradle
In the APOC Extended updates, I updated this to the latest version as 1.19.7 has a bug, better to update core directly over that bug to make sure we don't run into the same issues as extended!
> [NOID] Update testContainers

- common/src/main/java/apoc/util/Util.java
- common/src/test/java/apoc/util/UtilTest.java
Not able to add into the rest of the code base yet as they are only readable through Core API and not useable in any other way :) I made a card for the fixing the rest later.
> [rzjiVl4e] Add new Core API constraints

- build.gradle
- core/src/main/java/apoc/warmup/Warmup.java
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
Enables some extra assertions in kernel.
> [NOID] Kernel debug flag

- common/src/main/java/apoc/result/CypherStatementMapResult.java
- common/src/main/java/apoc/result/DataProgressInfo.java
- core/src/main/java/apoc/export/csv/CustomCSVWriter.java
- it/src/test/java/apoc/it/core/PeriodicIterateTest.java
A few license headers are missing.
This adds them.
> [9aSkAHkN] add missing license headers

- .github/workflows/traceability-comments-trigger.yaml
- .github/workflows/traceability-comments.yaml
Replace the old trello with the same one the monorepo uses :D
> Add new trello action

- common/src/main/java/apoc/ApocExtensionFactory.java
Cherry-pick: https://github.com/neo4j/apoc/pull/700
> Update to behave differently for APOC extended (#700)

- LICENSES.txt
- NOTICE.txt
- build.gradle
- core/src/main/java/apoc/help/HelpUtil.java
- core/src/main/java/apoc/schema/Schemas.java
- readme.adoc
> Version bump: 2025.01.0

- core/src/main/java/apoc/export/graphml/ExportGraphML.java
- core/src/test/resources/procedures/common/procedures.json
The config values were incorrect; [docs](https://github.com/neo4j/docs-apoc/pull/348)
> Fix config maps for graphml procs

- .github/workflows/CI.yaml
- .github/workflows/traceability-comments.yaml
We have been having compile issues with AWS returning NONE, Simon has given me this to hopefully fix it
> Update the way we fetch the Neo version

- .github/workflows/CI.yaml
- .github/workflows/traceability-comments.yaml
> 5.26 fix builds

- common/src/main/java/apoc/ApocExtensionFactory.java
- common/src/main/java/apoc/RegisterComponentFactory.java
Remove trigger handlers on db delete
> Remove resolvers on db shutdown

- common/src/main/java/apoc/ApocExtensionFactory.java
- common/src/main/java/apoc/RegisterComponentFactory.java
cherry-pick: https://github.com/neo4j/apoc/pull/724
> Remove resolvers on db shutdown (#724)

- common/src/main/java/apoc/export/util/LimitedSizeInputStream.java
Cherry picks fix from https://github.com/neo4j/apoc/pull/733.
> add close method to LimitedSizeInputStream

- core/src/test/java/apoc/periodic/PeriodicTest.java
Cherry-pick: https://github.com/neo4j/apoc/pull/732
> testTerminateCommit: stop test going out of memory (#732)

- test-utils/src/main/java/apoc/util/TestContainerUtil.java
Cherry pick of https://github.com/neo4j/apoc/pull/738
> Fix setting

- test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
From https://github.com/neo4j/apoc/pull/737
> Fix compilation error in DbmsRule

- common/build.gradle
Cherry-pick: https://github.com/neo4j/apoc/pull/740
> Bump dependency

- core/src/main/java/apoc/math/Maths.java
- core/src/test/resources/functions/common/functions.json
- core/src/test/resources/functions/cypher25/functions.json
- core/src/test/resources/functions/cypher5/functions.json
All of these are getting Cypher 25 support, so deprecate them :D
> Deprecated hyperbolic functions moved into Cypher

- core/src/test/java/apoc/periodic/PeriodicTest.java
- test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
- test-utils/src/main/java/apoc/util/TransactionTestUtil.java
Fix tests that spammed the db with queries and could become very long running.
> Fix long-running test assertions

- common/src/main/java/apoc/result/VirtualNode.java
- common/src/main/java/apoc/result/VirtualRelationship.java
- common/src/test/java/apoc/result/VirtualNodeTest.java
- core/src/main/java/apoc/trigger/TriggerMetadata.java
- core/src/test/java/apoc/graph/GraphsTest.java
- core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Fix trigger related ids for relationships and nodes
Cherry-pick: https://github.com/neo4j/apoc/pull/746
> Fix trigger related ids for relationships and nodes

- build.gradle
- core/build.gradle
Fixes https://github.com/neo4j/apoc/issues/690
> Add artifact that combines common and core

- core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Fixes: https://github.com/neo4j/apoc/issues/159
> Fix issue with import cast exception

- core/src/main/java/apoc/refactor/util/PropertiesManager.java
- core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Fixes: https://github.com/neo4j/apoc/issues/761
> Fix issue with empty arrays not being merged

- LICENSES.txt
- NOTICE.txt
- common/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
- common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
- common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
- common/src/main/java/org/neo4j/cypher/export/SubGraph.java
- core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
- core/src/main/java/apoc/export/json/JsonFormat.java
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Closes some resources that were left open before. Could potentially fix some flaky export tests.
- https://trello.com/c/gRSYmlRs/2615-nightly-test-failure-apocexportcypherexportcyphermultireltestcreateoptimizationnone-is-failing-in-a-pipeline-run
- https://trello.com/c/Il7Rm3eN/2605-nightly-test-failure-apocexportcypherexportcyphermultireltestaddstructurewithoptimization-is-failing-in-a-pipeline-run
- https://trello.com/c/OwcxoHDR/2612-merge-test-failure-apocexportcypherexportcyphermultireltestupdatestructurewithoptimization-is-failing-in-a-pipeline-run
- https://trello.com/c/XpmvYy8q/2613-merge-test-failure-apocexportcypherexportcyphermultireltestcreatewithoptimization-is-failing-in-a-pipeline-run
- https://trello.com/c/uHttAONj/2614-merge-test-failure-apocrefactorgraphrefactoringtestshou …
> Close resources

- build.gradle
- versions.json
Find the Neo4j versions above the integer release of 5 :)
> Fix to work with CalVer versions

- LICENSES.txt
- NOTICE.txt
- build.gradle
- licenses-3rdparties.gradle
> Bump dependencies

- common/src/main/java/apoc/meta/Types.java
- common/src/main/java/apoc/meta/tablesforlabels/PropertyTracker.java
- core/src/test/java/apoc/export/arrow/ArrowTest.java
- core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
- core/src/test/java/apoc/export/csv/ExportCsvTest.java
- core/src/test/java/apoc/meta/MetaTest.java
- core/src/test/java/apoc/refactor/CloneSubgraphTest.java
- it/src/test/java/apoc/it/core/ApocVersionsTest.java
Add support to Vectors in the Meta functions
> Add some vector support to APOC

- LICENSES.txt
- NOTICE.txt
- build.gradle
cf. https://github.com/neo-technology/neo4j/blob/dev/public/pom.xml#L1700-L1706
> Bump netty version

- common/build.gradle
Snyk test found an update we need to do
> Update google cloud storage

- LICENSES.txt
- NOTICE.txt
- build.gradle
- common/build.gradle
- test-utils/build.gradle
Cherry-pick dependency updates
> Update Google cloud storage (#821)

- core/src/test/java/apoc/schema/SchemasTest.java
There has been a change in the schema rule generated name algorithm.
> Update generated constraint name

- build.gradle
- common/build.gradle
- core/build.gradle
- greclipse.properties
- it/build.gradle
- licenses-3rdparties.gradle
- licenses-source-header.gradle
- processor/build.gradle
- teamcity-repository.gradle
- test-utils/build.gradle
- Fix a bug where the pom file output of publications was incorrect. We hand crafted the pom file, which did not work for bom dependencies, now we use the built in functionality to handle this instead.
- Refactor publications to simplify.
- Apply code style to gradle files.
> Fix publications

- core/build.gradle
- processor/build.gradle
Updated APOC manifests to include vendor and title.
> Updated manifest with more information
