neo4j/apoc

test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java

PR to be merged shortly after a change to upstream neo4j, so that apoc continues to compile after a package rename.
Renames an import in `DbmsRule` as the class in question has been moved in upstream neo4j.

Added import for upstream package change

---

common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/main/java/apoc/refactor/rename/Rename.java
core/src/main/java/apoc/schema/Schemas.java
core/src/test/java/apoc/refactor/GraphRefactoringTest.java
core/src/test/java/apoc/refactor/rename/RenameTest.java
core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
core/src/test/java/apoc/schema/SchemasTest.java
core/src/test/java/apoc/util/UtilTest.java

Back-ticks will be escaped to allow users to still have back-ticks in their labels, properties etc as in Cypher, without the risk of Cypher Injection.
This also fixes this issue: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3139

Sanitize back-ticks in strings when there is a possibility of Cypher injection

---

core/src/main/java/apoc/cypher/CypherInitializer.java

Using Config to resolve default db is correct in Community. In Enterprise:
* in 4.x it is correct in  standalone, but not in clusters (probably nobody noticed - given the troublesome past cluster vs. apoc).
* in 5.0 it is not correct. The config value represents the "initial" default database only. The topology graph knows better, as the default database is dynamically changeable.
This PR is a prerequisite for https://github.com/neo-technology/neo4j/pull/16699

Use DefaultDatabaseResolver to resolve default db (instead of Config)

---

common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/main/java/apoc/refactor/rename/Rename.java
core/src/main/java/apoc/schema/Schemas.java
core/src/test/java/apoc/util/UtilTest.java

Fixes:
- Too many escapes of the backslash
- No need to check for the actual ` and the unicode value
- But a need to check for the escaped unicode proper (which is literal \u0060, written down as Java String becomes \\u0060, no further escaping for the regex necessary

Improve backtick sanitization

---

common/src/main/java/apoc/ApocConfig.java
core/src/main/java/apoc/warmup/Warmup.java
core/src/test/java/apoc/warmup/WarmupEnterpriseTest.java
core/src/test/java/apoc/warmup/WarmupTest.java
docs/asciidoc/modules/ROOT/pages/overview/apoc.warmup/apoc.warmup.run.adoc

The apoc.warmup.run procedure can only be used with the currently available storage engines.
I've added a checker for checking which storage engine currently is set via config. Let me know thoughts on this! It is also possible to only have the docs updated :)

5.0 add storage engine check

---

build.gradle

This property was only being used by the `./gradlew versions` task which exists in the master branch.

Remove the neo4jVersions gradle property

---

build.gradle
docs/asciidoc/antora.yml
docs/build.gradle
readme.adoc

Everything we release in APOC is going to be "the latest version" and therefor downloadable by users. There isn't much value in calling these releases "release candidates" because they're real releases that will be used by ALL users.

Remove references to '-rc' releases

---

core/src/main/java/apoc/load/Xml.java
core/src/test/java/apoc/load/XmlTest.java

Makes XML procedures resistant to XXE attacks by following the general advice which is to disable External Entities. This is what we had done previously for apoc.load.xml and apoc.xml.parse, but forgot to do for apoc.import.xml.

[hcaaOlXR] Various security fixes

---

core/src/main/java/apoc/load/Xml.java
core/src/test/java/apoc/load/XmlTest.java
core/src/test/resources/xml/billion_laughs.xml

Protects fully against XXE and Billion Laugh attacks by following the following recommendations:
- [Owasp recommendation](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#xmlinputfactory-a-stax-parser) 
- [Leftshift recommendation](https://www.shiftleft.io/blog/preventing-xxe-in-java-applications-02-12-2021/#xmlinputfactory)

[hcaaOlXR] Protect from Billion Laughs

---

core/src/main/java/apoc/cypher/CypherInitializer.java
core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java

Startup log exception in Neo4j 5.x about 'Topology Graph is not initialized yet' 
- Check compatibility on the system database instead of the default database
- Make sure dbms.components() has been registered 
- Update compatibility warning message to apply to 5.x versioning

[9uFWHlVy] Check compatibility on system database instead of default database

---

build.gradle
readme.adoc

I copied what Nacho did in this 5.1.0 commit https://github.com/neo4j/apoc/commit/ca8663678a3dc5bf2477982e930723f7786a6503

[NOID] Bump Neo4j to 5.2.0

---

.github/workflows/CI.yaml

We've performed a Github Actions review of this repository and made changes to the default permissions offered to our Actions.
As a result, we must make this [recommended change](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#analyzing-python-dependencies) to the build job so that CodeQL can function without warnings.

[UHxIZ8JO] Grant CodeQL permissions

---

common/src/main/java/apoc/periodic/PeriodicUtils.java
core/src/main/java/apoc/periodic/Periodic.java
core/src/test/java/apoc/periodic/PeriodicTest.java

Fixes neo4j/apoc#126 (core part)
1) Added QueryType validations in `validateQuery()` method, so as to fail if the procedure tries to execute schema operations
2) Refactored `apoc.periodic.submit` code in order to be reused in extended.
3) In  https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3211, added `apoc.periodic.submitSchema` procedure, equivalent but with different `validateQuery()` and `org.neo4j.procedure.Mode.SCHEMA`
----
NOTE FOR REVIEWER:
- We could also create a schema equivalent for the others periodic procedures (maybe in another issue/pr?)
- Even the `apoc.trigger.add` has the `validateQuery()`, maybe can be changed in the same way? (also in this case, perhaps in another pr)

Fixes neo4j/apoc#126: apoc.periodic.submit fails with schema operations (core)

---

core/src/test/java/apoc/text/StringsTest.java

Before this PR test was expecting the incorrect value of distance.
As a result, https://issues.apache.org/jira/browse/TEXT-191 and the new commons-text test
is updated with the correct expected value.

Update testJaroWinklerDistance test expectation

---

core/src/main/java/apoc/refactor/rename/Rename.java
core/src/test/java/apoc/refactor/rename/RenameTest.java

Fixes #26
The same bug also affects relationship types in `apoc.refactor.rename.type` and properties in `apoc.refactor.rename.nodeProperty` / `apoc.refactor.rename.relProperty`.

[pDw6xmRG] Fixes #26: apoc.refactor.rename.label delets label if oldLabel is equal to newLabel

---

common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/periodic/Periodic.java
core/src/test/java/apoc/periodic/PeriodicTest.java

After this cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3234,
I realized that the validateQuery doesn't work with an inner `org.neo4j.procedure.Mode.SCHEMA` procedure, e.g. `CALL db.createUniquePropertyConstraint`,
so I improved it to check these situations.
The `validateQuery` still has some limitations, for example it does not catch cases like this `CALL apoc.cypher.run (\" CALL apoc.schema.assert ({}, {}) \ ", {}) YIELD value RETURN value`, with a sub-inner schema procedure,
or I might have a `call apoc.cypher.runSchema ('return 1', {})` which even though it's a `Mode.SCHEMA`, doesn't actually perform schema operations (even if it doesn't make much sense).
Perhaps, in some way, the above 2 cases can also be validated,
but I think they could be very complex to …

Fixes #126: Improve validateQuery

---

build.gradle

It looks like this was never actually run before as Neo4j releases have been empty until now.

Iterate over apoc release tag names

---

build.gradle

So we found some new issues 😅
As neo4j versions are not going to show past ones, we think we need to update how the script adds versions, we have made some assumptions for how this works, let me know if you need to discuss it more :)

[NOID] 5.x fix apoc versions script 2

---

core/src/main/java/apoc/cypher/CypherInitializer.java
core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java
test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java

This has been requested by Neo4j Aura, which couldn't see if the procedure call came from APOC or a user

[4HrPR2Rm] Use internal function instead of procedure for compatibility check.

---

.github/workflows/CI.yaml
common/build.gradle
core/build.gradle
core/src/main/java/apoc/export/csv/CsvEntityLoader.java
teamcity-repository.gradle
test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java

Cherry-picks #226 
* Moves commons-configuration2 dependency to compileOnly
This dependency was importing commons-text 1.9.0 which has the CVE-2022-42889 vulnerability. Since this dependency is imported by Neo4j at runtime, I've decided to simply not include it in the APOC runtime.
* Bumps openCsv to 5.7.1
OpenCsv has made a number of breaking change between 4.x and 5.x:
- you must now use the builder constructor
- you should now wrap the csv reader in a try-with-resources
https://opencsv.sourceforge.net/#upgrading_from_4_x_to_5_x

[NOID] Fixes CVE-2022-42889 in transitive dependencies

---

build.gradle
versions.json

The automatic job for updating `versions.json` is not working as we expected. It should have written:
* neo4j 5.0.0 -> apoc 5.0.0
* neo4j 5.1.0 -> apoc 5.1.0
* neo4j 5.2.0 (not in Maven Central yet) -> apoc 5.2.1
but instead has written:
* neo4j 5.0.0 -> apoc 5.2.1
* neo4j 5.1.0 -> apoc 5.2.1
This PR fixes the `versions.json` manually.

[NOID] Corrects versioning manually until automatic job is fixed

---

build.gradle

Take into account both major and minor version, always use the most recent patch of APOC for each major.minor version of APOC

[ahK775nK] Take into account minor versions for versions.json

---

.github/workflows/CI.yaml
build.gradle

Changed gradle versions in order to build extended library 
See https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3284
Currently extended fails with `org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.neo4j:neo4j:5.1.0-dev` error, because in `CoreExtendedTest` is executed  an `TestContainerUtil.executeGradleTasks(projectDir, "shadowJar");` of the core project, but doesn't find neo4j (because neo4jVersionEffective in `apoc-core/build.gradle` is  "5.1.0-dev" )
---
Updated `ci.yaml` from "dev" to "5.1.0" in order to run the CI.

Changed gradle version in order to build extended library

---

build.gradle
test-utils/src/main/java/apoc/util/TestContainerUtil.java

From neo4j 5.2, passwords now have to be 8 characters minimum length

Fixes password length, bumps testContainer version

---

core/src/test/java/apoc/load/LoadJsonTest.java

The `json` disappeared from the external service. There's still another test that loads a json from stackexchange, so that should be enough to test the functionality.
These files should be moved to the repo probably and accessed through a github url rather than depending on external services.

[NOID] Removes load json test, the data is not in the external API anymore

---

core/src/test/java/apoc/spatial/GeocodeTest.java

Currently the tests, except for the `"osm"` one, are quite unusable.
In fact, the `"opencage"` tests are actually ignored due to [this assumption](https://github.com/neo4j/apoc/compare/fix_ignored_testGeocodeGoogle?expand=1#diff-252f4d56949dc064efccfe8ec2a9f918c432ad1b2a224973c2fc2b9e499e90d1L84), 
so in order to run them, we should manually writ your own key instead of `<YOUR_API_KEY>`.
While the reverse `"google"` test is a false positive, as it returns (with an invalid/absent ket) an empty result and [here](https://github.com/neo4j/apoc/compare/fix_ignored_testGeocodeGoogle?expand=1#diff-252f4d56949dc064efccfe8ec2a9f918c432ad1b2a224973c2fc2b9e499e90d1L137) the return result works even if it shouldn't. 
There should be a `assertTrue(row.hasNext());` before the foreach.
So to make these …

[4Bmcyc2U] Fix ignored testGeocodeGoogle

---

.github/workflows/CI.yaml
common/build.gradle
test-utils/build.gradle

Installs Snyk for PRs. There are three different Snyk jobs:
- Snyk test: tests for dependencies and licenses. Triggered on PRs and on merges to dev.
- code/snyk: not defined in this PR. The repo was imported manually. This will analyze the code included in the PRs for security vulnerabilities (unsafe patterns for example).
- Snyk monitor: allows us to monitor the project from https://app.snyk.io. Creates a snapshot of the list of dependencies and will ping us when bleeding edge new vulnerabilities are associated to those. Only runs when pushing to dev.
Because we want to increase how safe the code is and be alerted about the bleeding edge vulnerabilities.

[eRGoCYQI] Installs Snyk monitor GitHub action on PRs

---

.github/workflows/CI.yaml
common/build.gradle
core/build.gradle
core/src/test/java/apoc/load/XmlTest.java
core/src/test/java/apoc/refactor/CloneSubgraphTest.java
core/src/test/java/apoc/text/StringsTest.java
core/src/test/java/apoc/trigger/TriggerDisabledTest.java
test-utils/build.gradle

* Bumps the policy for dependency Snyk tests to medium level
* Fixes the dependencies that make that fail
* Makes monitor use the dev branch to group projects. This will make it easier to navigate if we have to add 6.x code to this repo. We would end up with something similar to this in the Snyk UI, but for this repo

[eRGoCYQI] Fixes all Snyk dependency issues of medium security level

---

.github/workflows/CI.yaml

Changes `GITHUB_REF_NAME` for `GITHUB_REF` because the first one is only populated for PRs.
Because Snyk is complaining that the target reference is empty for the monitor job on master:

[eRGoCYQI] Solves problem with empty GITHUB_REF for branches

---

common/src/main/java/apoc/result/IndexConstraintNodeInfo.java
common/src/main/java/apoc/result/IndexConstraintRelationshipInfo.java
core/src/main/java/apoc/schema/Schemas.java
core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
core/src/test/java/apoc/schema/SchemasTest.java

For consistency with the `apoc. schema.nodes`, I put `"INDEX"` instead of relType.
I've put the old `"type"` in a new field `"relationshipType"`, in order not to lose output info and to be consistent with `"label"` in `schema.nodes` proc (I don't know if it can be considered an additional feature).
To discuss:
In any case, maybe, in both nodes and relationships procedure, instead of get only "INDEX" we could use `IndexDescriptor.getIndexType()` to get a more comprehensive "FULLTEXT"/"LOOKUP"/"TEXT"/"RANGE" or "POINT".
Most likely, since it's a feature, this change could be done in another card, in case.

[Zl3h9sM8] apoc.schema.relationships return wrong output for relationship indexes

---

common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
common/src/main/java/apoc/result/VirtualNode.java
common/src/main/java/apoc/result/VirtualRelationship.java
common/src/main/java/apoc/result/WrappedNode.java
common/src/main/java/apoc/util/Util.java
common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
common/src/test/java/apoc/result/VirtualNodeTest.java
core/src/main/java/apoc/export/arrow/ExportResultStrategy.java
core/src/main/java/apoc/export/csv/CsvEntityLoader.java
core/src/main/java/apoc/export/csv/CsvFormat.java
core/src/main/java/apoc/export/csv/ExportCSV.java
core/src/main/java/apoc/export/csv/ImportCsv.java
core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
core/src/main/java/apoc/meta/Meta.java
core/src/main/java/apoc/neighbors/Neighbors.java
core/src/main/java/apoc/path/PathExplorer.java
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/main/java/apoc/refactor/util/RefactorUtil.java
core/src/main/java/apoc/spatial/Distance.java
core/src/test/java/apoc/number/exact/ExactTest.java
core/src/test/java/apoc/refactor/GraphRefactoringTest.java

Replace most instances of getId, getNodeByID or getRelById etc as they are deprecated for removal.
This isn't all cases, there are about 20 left still, but this was all I had time for on cleanup (plus the last ones are hard :P )

Remove use of getID

---

common/src/test/java/apoc/util/DateParseUtilTest.java
common/src/test/java/apoc/util/UtilIT.java
core/src/main/java/apoc/atomic/Atomic.java
core/src/test/java/apoc/atomic/AtomicTest.java
core/src/test/java/apoc/export/ExportStreamsStatementsTest.java
core/src/test/java/apoc/export/csv/ExportCsvIT.java
core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
core/src/test/java/apoc/export/csv/ImportCsvTest.java
core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
core/src/test/java/apoc/hashing/FingerprintingTest.java
core/src/test/java/apoc/load/LoadJsonTest.java
core/src/test/java/apoc/load/XmlTest.java
core/src/test/java/apoc/meta/CollEnterpriseTest.java
core/src/test/java/apoc/path/PathsTest.java
core/src/test/java/apoc/periodic/PeriodicTest.java
core/src/test/java/apoc/refactor/GraphRefactoringTest.java
core/src/test/java/apoc/spatial/GeocodeTest.java
core/src/test/java/apoc/spatial/SpatialTest.java
core/src/test/java/apoc/trigger/TriggerTest.java
core/src/test/java/apoc/util/UtilTest.java
core/src/test/java/apoc/util/UtilsTest.java
core/src/test/java/apoc/warmup/WarmupEnterpriseTest.java

Tests with '(expected = QueryExecutionException.class)' or similar can
fail with the correct exception for unrelated reasons before coming to the assertion, making the test green even if it is broken. Also ignoreExceptions() feels dangerous to have in test setups 
Builds on top of https://github.com/neo4j/apoc/pull/240

[NwnPuJ91] Rewrite tests for failures in a safer way

---

.github/workflows/traceability.yml
readme.adoc

Adds https://github.com/neo4j/github-action-traceability to the APOC CI. You may wish to review the code in my custom Github Action since nobody has reviewed that code.

[i19tvtq1] Add Trello Traceability GHA to the CI

---

common/build.gradle
test-startup/src/test/java/StartupTest.java
test-utils/build.gradle
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Because we were seeing messages like this one on startup:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

[MiVboeTJ] Fixes slf4j apoc logger

---

test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java

Just to be sure, I re-triggered the CI Build 3/4 times, with no errors
-----
Try fixing the following (flaky?) cluster error, like in [this pr](https://github.com/neo4j/apoc/pull/278) or in [this other one](https://github.com/neo4j/apoc/pull/283)
```
apoc.trigger.TriggerClusterRoutingTest > testTriggerDropAllowedOnlyInSysLeaderMember STANDARD_ERROR
[Thread-407] ERROR 🐳 [neo4j:5.4.0-enterprise] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:49196/db/neo4j/cluster/available should return HTTP 200)
at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:318)
....
....other stuff
....
Error: Process completed with exit code 1.
```

[NOID] Try fixing cluster failing test

---

core/src/main/java/apoc/index/SchemaIndex.java
core/src/test/java/apoc/index/SchemaIndexTest.java

The test cases about 2nd scenario (ie fulltext indexes) is to be completed,
because it is to understand if the solution is good or not,
as it is in limbo between a bugfix and a feature.
That is, currently fulltext indexes are just not supported, hence the infinite hang.
To solve I created several `if(isFulltexIndexes) { fullTextImplementation } else { currentImplementation}`.
Alternatively we can do something like `if(isFulltexIndexes) { skipCurrentFulltextIndex }`, and document this.
But I think this is not a correct behavior, because as a user I would expect `apoc.schema.properties` to support any type of index, so maybe this is a bugfix and not a feature.
Wdyt?

[ADJvoENI] apoc.schema.properties.distinct(Count) can hang

---

common/src/main/java/apoc/util/FileUtils.java
core/src/main/java/apoc/export/csv/ExportCSV.java
core/src/test/java/apoc/export/ExportCoreSecurityTest.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java
core/src/test/java/apoc/export/json/ExportJsonTest.java

vuln-fix: Fixes path traversal vulnerability (CVE-2022-23532)
Impact: APOC export procedures were vulnerable to path traversal which could result in files being written to outside of the control directory.

[vFQk1rX0] vuln-fix: Fix path traversal vulnerability (CVE-2022-23532)

---

core/src/main/java/apoc/text/Strings.java
core/src/main/java/apoc/util/Utils.java

During the Threat Modelling it was decided that apoc.util.sha1 and apoc.text.random should be documented as unsafe for cryptographic use to discourage users from thinking they are secure.

[126ZorO2] Document that apoc.util.sha1 and apoc.text.random are not suitable for cryptographic use.

---

test-utils/src/main/java/apoc/trigger/TriggerTestUtil.java

In 4.4 [I increased this value](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3355), and in this way the problem seems to be resolved.
In 5.x [I tried to put a lower value](https://github.com/neo4j/apoc/pull/250#discussion_r1060649214), 
but apparently some tests are flaky.
As with 4.4, I couldn't figure out exactly why this stabilize the tests (hoping it's for the same reason as 4.4), 
also because the problem seems to occur only with the embedded instance 
(i.e. `org.neo4j.test.TestDatabaseManagementServiceBuilder` )

[480BDuYi] Try de-flake some trigger tests with embedded db

---

core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java

Related to https://github.com/neo4j/docs-apoc/pull/90
With `before` the `$transactionId` always returns `-1` because the [txData.getTransactionId()](https://github.com/neo4j/apoc/blob/dev/core/src/main/java/apoc/trigger/TriggerMetadata.java#L69) throws an `java.lang.IllegalStateException: Transaction id is not assigned yet. It will be assigned during transaction commit.`.
The example with 'after', is slightly different than the one on the related Trello card because in that way would causes a deadlock.
I created a card to track of this behavior `[H5vz3qhy]`.

[yHvDctRN] Add tests and docs about $transactionId

---

test-utils/src/main/java/apoc/util/s3/S3TestUtil.java

My guess is that sometimes the `localstack` container doesn't load the file immediately, hence the `The specified key does not exist` error.
Hopefully, this could also solve the `zKSByYcV` (ExportCypherS3Test.testExportQueryCypherFormatUpdateAll), 
where I think the file is not immediately overwritten
but a previous `all.cypher` file coming from another test is retrieved.

[0eSjZq6Q] Fix S3 failing flaky tests

---

test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java

I don't know if it can be really related, but the `(value) -> true` makes the assertion always green 
even if the `killPeriodicQueryAsync(db);` just before is deleted.

[KrJWRWJD] Fix flaky testTerminatePeriodicQuery

---

common/build.gradle

Cherry pick (only gradle comment) https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/bf1b662a0663c851708ff3981d47abe92876f689

[NOID] Fix docs cve 2021-27568 (neo4j-contrib/neo4j-apoc-procedures#2953)

---

common/src/main/java/apoc/export/cypher/FileManagerFactory.java
core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java

Cherry-pick  https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/194ca2aa877d67fc699c828ddde97d56ec414eb7

[NOID] Fixes neo4j-contrib/neo4j-apoc-procedures#3070: The apoc.export.csv.all with bulkImport config doesn't work with a file name without extension

---

core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
core/src/main/java/apoc/trigger/TriggerNewProcedures.java
core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java

- The `apoc.trogger.drop`, `apoc.trogger.stop` and `apoc.trogger.start` return an empty result if the trigger doesn't exist
- The `apoc.trigger.install` returns the current trigger instead of the previous one

[gcL5e77c] Fix edge cases in trigger methods

---

core/src/main/java/apoc/diff/Diff.java
core/src/test/java/apoc/diff/DiffTest.java

Fixes neo4j-contrib/neo4j-apoc-procedures#2992
Cherry-pick:  https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b069e2bfd51b3015d29452aeddda6059cff6bc0f

[NOID] Fixes neo4j-contrib/neo4j-apoc-procedures#2992: apoc.diff.nodes() returns list-type properties as different when they are the same

---

core/build.gradle
test-utils/build.gradle

Bumps versions to fix vulnerabilities (no CVE present)

[4cnpX39y] Bump mockserver-netty version and org.apache.arrow version

---

core/src/main/java/apoc/algo/Cover.java

Use a hashset instead to improve performance of contains for larger node lists.

[HQABUD5U] Improve coverNodes speed

---

common/src/main/java/apoc/export/util/BatchTransaction.java
core/src/main/java/apoc/export/csv/CsvEntityLoader.java
core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
core/src/test/java/apoc/export/csv/ImportCsvTest.java
core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java

Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/dd6579b3108f4cddb6a828b382de34e1aef148fc

[NOID] Fixes #2826: The apoc.import.csv/graphml procedures create empty wrong empty nodes with UNIQUE constraint violation (#3006)

---

common/src/main/java/apoc/ApocConfig.java
common/src/main/java/apoc/util/Util.java

Depends on changes that need to go in the dbms.
Avoids an extra DNS resolve by replacing the domain with the resolved ip address.

[mIPA5H7K] Avoids double DNS lookup in the load methods

---

core/src/main/java/apoc/schema/Schemas.java
core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
core/src/test/java/apoc/schema/SchemasTest.java

Changed `ConstraintDescriptor` to `ConstraintDefinition` in `nodeInfoFromConstraintDefinition`.
This to be consistent with `relationshipInfoFromConstraintDefinition` and to retrieve the constraint type with `constraintDefinition.getConstraintType().name()`, easier to implement and not internal.
The only con is that to get the "userDescriptor" output I have to use this method `ktx.schemaRead().constraintGetForName(constraintDefinition.getName()).userDescription(tokens)`.
Alternatively, I could remain ConstraintDescriptor and derive the type of constraint via a method like this, but it's not future-proof:
```
public static ConstraintType getConstraintType(ConstraintDescriptor descriptor) {
if (descriptor.isNodeUniquenessConstraint()) return ConstraintType.UNIQUENESS;
if …
```

[hZww9vSJ] Make the type output of apoc.schema.* procedures more specific

---

core/src/test/java/apoc/spatial/GeocodeTest.java

- Added failing tests for ip blocklist setting.
It's not necessary to change the implementation, 
as both `apoc.spatial.geocode` and `apoc.spatial.reverseGeocode` call `JsonUtil.loadJson(...)` 
which ends up on the work done [in this pr](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2649).

[wvzcpHQH] Add SSFR check for apoc.spatial procedures

---

core/src/main/java/apoc/spatial/Geocode.java

Changed "throttle" configuration by using `config` (like the above values) instead of `apocConfig()`.
I cannot add a non-mocked test to check the change in junit,
because e.g. an opencage api key would be needed to run the query successfully.

[NOID] Fix wrong throttle config in Geocode.SupplierWithKey

---

.github/actions/test-gradle-project/action.yaml
gradle.properties

Keeps it in GitHub Actions.
Because TeamCity seems to not be very happy with it at the minute. Probably because all projects get executed at the same time, rather than the parallelism been intra-project, like in GitHub Actions

[F61iNGQX] Removes parallel execution in TeamCity

---

core/src/test/java/apoc/periodic/PeriodicTest.java
test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java

I didn't notice it at first glance because locally it works even without the fix.
However the inner query was wrong because it returned a node, instead it is supposed to return a long.
My guess is that it's a timing problem, because if for example we remove the `limit 1000` the query fails almost immediately,
while with `return n` instead of `return count(n)` it fails after a while.
So probably doing `markForTermination()` almost at the same time as it fails causes the flaky assertion error.

[bJ4pn0Bj] PeriodicTest.testTerminateCommit is flaky

---

core/src/main/java/apoc/hashing/Fingerprinting.java
core/src/test/java/apoc/hashing/FingerprintingTest.java

[OnEGwZ5A] apoc.hashing.fingerprint can't deal with type byte[]

[OnEGwZ5A] apoc.hashing.fingerprint can't deal with type byte[]

---

core/src/main/java/apoc/schema/SchemaConfig.java
core/src/test/java/apoc/schema/SchemasTest.java
it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java

Since the config keys are case sensitive, these error messages are wrong:
```
Parameters relationships and excluderelationships are both valuated. 
Parameters labels and excludelabels are both valuated.
```

[NOID] Fix error message for apoc.schema.nodes/relationships with include and exclude confs both valuated

---

common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
core/src/main/java/apoc/trigger/TriggerNewProcedures.java

The ideal solution I suppose is to use `@Context public Transaction tx`, which calls `ProcedureTransactionImpl`.
But with both this and `@Context publicGraphDatabaseAPI` [which calls ProcedureGraphDatabaseAPI] via `db.beginTx()`,
I receive the following error if I login with an user with role `admin` 
(both with the embedded db and with an enterprise instance):
```
Creating new node label on database 'system' is not allowed for user '' 
with FULL overridden by READ overridden by READ. See GRANT CREATE NEW NODE LABEL ON DATABASE system
```
Btw, even trying to explicit `GRANT CREATE NEW NODE LABEL ON DATABASE system TO admin` gives the same result.
I also tried changing `mode = Mode.WRITE` to `Mode.DBMS` but it doesn't change anything.
I think the above one might be a bug, or so, not APOC …

[ROQ0fkdz] Reduce the number of transactions we use in triggers

---

it/build.gradle

Because these tests spin up a lot of docker containers, especially in TeamCity, which can lead to flakiness

[F61iNGQX] Executes integration tests sequentially

---

core/src/main/java/apoc/create/Create.java
core/src/test/java/apoc/create/CreateTest.java

Added cache for `apoc.create.clonePathsToVirtual` in order to reuse the same virtual rel if already present,
so we don't visualize multiple relationships

[iTwFvqQ2] apoc.create.clonePathsToVirtual() returns more relationships than it should

---

common/build.gradle
core/src/test/java/apoc/hashing/FingerprintingTest.java
it/build.gradle
test-utils/build.gradle

Cherry-pick of core parts of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3485

[nw2aWxrX] Upgrade aws-java-sdk-s3 to 1.12.425 to partially address CVE-2022-42003

---

core/src/test/java/apoc/periodic/PeriodicTest.java

The test `PeriodicTest` has been very strict about what error message to expect from the parser. This restricts us in changing the parser while it brings very little value to the user.
This change therefore proposes to only test for the relevant parts of the error message.
Co-authored-by: Gem Lamont <gemma.lamont@neotechnology.com>

[NOID] Making PeriodicTest more lenient

---

core/src/main/java/apoc/cypher/CypherInitializer.java

In order to avoid relying on internal implementation details of GlobalProceduresRegistry and its initialization.
- Use `GraphDatabaseService.isAvailable` to check for database availability, in favour of checking the registered procedures.

[h4782lRw] Use GraphDatabaseService primitives to check db state

---

common/build.gradle
test-utils/build.gradle

Updates Hadoop and JsonPath dependencies to their newest releases. The test coverage for these isn't great, but I couldn't see any breaking changes in the changelogs for them.

[tq7tdrWZ] Update Hadoop and JsonPath dependencies

---

common/src/main/java/apoc/util/Util.java
common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
core/src/main/java/apoc/export/csv/CsvFormat.java
core/src/main/java/apoc/export/json/JsonFormat.java
core/src/test/java/apoc/export/ExportCoreSecurityTest.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java
core/src/test/java/apoc/export/cypher/ExportCypherTest.java
core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
core/src/test/java/apoc/export/json/ExportJsonTest.java
core/src/test/java/apoc/load/LoadCoreSecurityTest.java
test-utils/src/main/java/apoc/util/TestUtil.java

When trying to use SHOW CONSTRAINTS or SHOW INDEXES, it looks like the current user doesn't have permission to use it instead of the procedure, this adds a more generic error message.

[1gsD8V8g] Add a more useful error message for export functions

---

core/src/main/java/apoc/trigger/TriggerHandler.java
core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java

Added a `CALL tx.setMetaData(<TRIGGER_META>)` procedure in transactions with phase `after` and `afterAsync`,
in order to prevent cascade trigger transactions coming from `TriggerHandler` itself,
so that we can avoid some deadlock conditions.
---
I don't know if it is somehow directly related to this pr,
but I had to change the `testRemoveNode` too, 
because it sometimes failed as the previous `CREATE (f:Foo)` had id = 0.

[H5vz3qhy] Prevent cascade trigger transactions

---

it/src/test/java/apoc/it/core/StartupTest.java
processor/src/main/java/apoc/processor/ExtensionClassWriter.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Cherry-pick (core part) of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3450
Extended part: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3454.
- Because of split, now we have 2 equivalent `apoc.ApocSignatures` which collect the list of procedures and functions, 
one for core and one for extended, so I added a `String projectPath` in order to create 2 different classes (`ApocSignaturesCore` and `ApocSignaturesExtended`).
- Created a `copyFilesToPlugin(..)` to be reused in Extended
- Changed baseDir, pluginsFolder and extendedDir to public, reusable in Ext. too

[TOQo1n9M] Core part - apoc-hadoop dependency is conflicting 5.x (neo4j-contrib/neo4j-apoc-procedures#3450)

---

common/build.gradle

This was reported as a vulnerability for 4.4, solved here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3522
Thought it wouldn't hurt to upgrade the dependency in 5.x as well.

[ST3nW88b] Upgrade commons-configuration2 to 2.9.0.

---

core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/test/java/apoc/refactor/GraphRefactoringTest.java

Added labels at the end of the `mergeNodes()` method, to prevent schema conflicts

[bZQoGhFu] apoc.refactor.mergeNodes is not working with uniqueness index

---

core/src/main/java/apoc/export/csv/CsvEntityLoader.java
core/src/main/java/apoc/export/csv/ImportCsv.java
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/test/java/apoc/cypher/CypherTest.java
core/src/test/java/apoc/export/BigGraphTest.java
core/src/test/java/apoc/export/csv/ImportCsvTest.java
core/src/test/java/apoc/export/json/ImportJsonTest.java
core/src/test/java/apoc/load/LoadJsonTest.java
core/src/test/java/apoc/load/XmlTest.java
test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
test-utils/src/main/java/apoc/util/TransactionTestUtil.java

- Added `TerminationGuard` to `apoc.import.csv`
---
The test didn't fail because it produced a false positive, 
since without the TerminationGuard, the procedure complete the whole procedure when the `TERMINATE TRANSACTION <procTransactionId>` is called, but despite this an `"Explicitly terminated by the user."` is eventually returned.
Therefore, with procedure duration less than the set `db.transaction.timeout`, 
both with and without the TerminationGuard, the test was green.
Apparently I didn't replicate it because, unlike gh actions and locally, 
with teamcity sometimes the procedure lasts more then `timeout` time.
So, I added an additional check to `checkTerminationGuard`, 
to verify that the procedure actually lasts longer than the timeout 
and I weighted the …

[Bc2lkk3N] Fixed testImportCsvTerminate and added TerminationGuard to apoc.import.csv

---

common/src/main/java/apoc/ApocConfig.java
core/src/main/java/apoc/export/arrow/ExportArrowService.java
core/src/test/java/apoc/export/ExportCoreSecurityTest.java
core/src/test/java/apoc/export/arrow/ArrowTest.java
core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java

Added check for procedures using file mode

[3QAbWQds] apoc.export.arrow.all ignores export file config

---

common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
common/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
common/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
common/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
common/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
common/src/main/java/org/neo4j/cypher/export/SubGraph.java
common/src/test/resources/init_neo4j_export_csv.cypher
core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
core/src/test/java/apoc/export/cypher/ExportCypherTest.java
core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java
it/src/test/java/apoc/it/core/ExportCypherS3Test.java

Fixes #345 
`apoc.export.cypher.all` exported some constraints with wrong type or not at all
A brief list of proposed changes in order to fix the issue:
- Stop classifying composite UNIQUE constraints as NODE KEY.
- Stop classifying single NODE KEY constraints as UNIQUE.
- Support existence constraints.
- Support relationship constraints.

[f46vahOr] Fix Cypher export of constraints

---

core/src/test/java/apoc/spatial/GeocodeTest.java

Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/7a9fec44a5fcaabbd6c296f21efdc8e509b9d239

[NOID] Fix flaky geocode server errors (neo4j-contrib/neo4j-apoc-procedures#3527)

---

core/src/main/java/apoc/cypher/Timeboxed.java
core/src/test/java/apoc/cypher/CypherTest.java
test-utils/src/main/java/apoc/util/TransactionTestUtil.java

If the inner query throws an error, 
the `apoc.cypher.runTimeboxed(...)` continues the execution until the `timeout` terminates.

[EaALzior] runTimeboxed doesn't always work

---

build.gradle
common/build.gradle
core/build.gradle

Removed `antlr4` and `generateGrammarSource` (which is only used by `apoc.custom*` extended).
No need to change Extended, 
since `generateGrammarSource` and `antlr` are already included in `extended/build.gradle`

[hyxhNENW] remove antlr4 from core

---

common/src/main/java/apoc/result/VirtualPath.java
core/src/test/java/apoc/create/CreateTest.java

The relationship check should verify either the start or the end node

[eBlQUOcs] Bug in apoc.create.cloneToVirtual

---

common/src/main/java/apoc/util/FileUtils.java
common/src/main/java/apoc/util/Util.java

- Changed export procedures to handle path consistently with imports
- Added a note for windows user is case of a `c:/path/to/file`.
---
Tested directly on windows.
It would be great to add tests for both windows and unix path, 
but I tried adding tests to emulate a windows path (e.g. with [this one](https://github.com/google/jimfs)), 
and they don't work properly.
Maybe we can create a separate card to try to add them?

[ZkSGN6PO] apoc.export.graphml.all doesn't accept absolute Windows paths

---

build.gradle
common/src/main/java/apoc/ApocExtensionFactory.java
core/src/main/java/apoc/CoreApocGlobalComponents.java
core/src/main/java/apoc/cypher/CypherInitializer.java
core/src/test/java/apoc/trigger/TriggerRestartTest.java
it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java

Implemented 3rd solution - `DatabaseEventListener`,
so that we can delete every system node belonging to the database that we delete.
Added a `cleanUpSystemNodes()` for backward compatibility

[madSHaLz] APOC triggers aren't updated after a user deletes a database

---

core/src/test/java/apoc/meta/MetaTest.java
core/src/test/java/apoc/schema/SchemasTest.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Removes usage of the feature flag for relationship constraints. This flag has been switched to true already, so removing this won't break, as well as allow a safe removal of the flag in the other code base :)
See [here](https://github.com/neo4j/apoc/pull/270/files) for original PR!

[MCKik4qR] Remove Relationship Constraint Feature Flag

---

core/src/main/java/apoc/cypher/CypherInitializer.java
it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java

Adding listeners to each database can cause nodes from user databases to be removed, as well as cause issues with concurrent drop database commands.

[D2VH2D8O] Only create trigger listeners on system db.

---

common/src/main/java/apoc/util/Util.java

apoc will still compile if new constraint types are added, but then needs to be updated with support for these types before they are available for use.

[NOID] Allow new constraint types to be introduced

---

common/src/main/java/apoc/periodic/PeriodicUtils.java
core/src/main/java/apoc/periodic/Periodic.java
core/src/test/java/apoc/periodic/PeriodicTest.java

Fixes #17
Most likely the bug occurs when there is a `RETURN ...` preceded by a void procedure with mode = "READ" (like the related gh issue)
- Added `Result::resultAsString` in order to consume results with void procedures.
- Check that the `db.prepareForReplanning` (which is a void read procedure) logs correctly

[gULAAkri] apoc.periodic.repeat doesn't always work

---

core/src/main/java/apoc/meta/Meta.java

Fixes #117
improve the documentation for the apoc.meta.* classes and methods. 
A brief list of proposed changes in order to fix the issue:
- Method Javadoc 
- Class Javadoc (very brief)
- "@params" to few methods to improve readability

Documenting apoc.meta.* 

---

build.gradle
common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/coll/Coll.java
core/src/test/java/apoc/coll/CollTest.java

Potentially this behaviour can affect a lot of procedures/functions, both `apoc.coll` and elsewhere.
I changed some of them, just to discuss about a possible solution that can be good for each procedure/fun that may have the problem.
For the other cases I created a follow-up card (id: `v8imq7eo`)
I think the possible solution are:
- Util.toAnyValues(..), as done in `apoc.coll.toSet`, which transform every object in `AnyValue`
- pros: less code to change, just wrap the lists with that method
- cons: tranform Object in AnyValue, so e.g an hardcoded `[1,2,3]` is converted from ArrayList<Long> to long[], so it could be considered a breaking change
- 
- Create Util method that leverage `ValueUtils.of()`, as done in `apoc.coll.indexOf` and `apoc.coll.containsAll` 
- pros: no need to loop …

[dITjfMpu] apoc.coll.indexOf unexpectedly treats collections differently than the same hardcoded list

---

common/src/main/java/apoc/util/Util.java
common/src/test/java/apoc/util/UtilTest.java
core/src/main/java/apoc/schema/Schemas.java
it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Add support for new type constraints as well as tests.
I also noticed that the unique column was not correct for constraints that were being dropped, so fixed that (so the behaviour is the same for created/dropped constraints of the same type)

[fdGuLCUX] Add type constraint support

---

build.gradle

Cherry picks https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3595
A dedicated property `neo4jDockerVersionOverride` has been created in TeamCity so we can pass a different version for neo4j and neo4j docker. This means we could be building with neo4j 4.4.22 when docker is still at 4.4.21
Because in some instances the docker job will not have the same neo4j version, since there's a circular dependency where in apoc we depend on docker and to build a docker container we depend on apoc been built and packaged with the database.
https://github.com/neo4j/apoc/pull/395 seemed to broke the TeamCity CI for 4.4

[NOID] Fixes circular docker dependency in TeamCity

---

core/src/main/java/apoc/atomic/Atomic.java
core/src/test/java/apoc/atomic/AtomicTest.java

Properties can use special characters, and they should be able to be updated via Atomic.update (and all other atomic procedures)

[KUEoGBey] Sanitize text input and add quotes to allow special characters in Atomic procedures

---

build.gradle

The builds are running for 3.5h instead of 25mins, reverting the most likely culprit.
Revert: https://github.com/neo4j/apoc/pull/426

[NOID] Revert docker gradle change

---

build.gradle

This reverts #434
Because what it was making it fail should have already been fixed at TeamCity level.

[NOID] Re-enable docker version override

---

core/src/main/java/apoc/path/LabelMatcher.java
core/src/test/java/apoc/path/ExpandPathTest.java

Unlike what is written in the card, 
the issue regards the `:` character, which handle compound labels.
---
In this pr I updated the `:` char so that an escape character `\` can be inserted.
In case it's ok, the documentation should be updated.
Otherwise, we could just explain better that the `:` char 
is used to handle multiple labels and that it is not possible to filter labels containing that character.

[rGkwaqu1] apoc.path.expand doesn't handle special characters in label name

---

build.gradle

The images have changed internally to have the `-debian` tag

[NOID] Uses debian images in the TeamCity CI

---

common/src/test/java/apoc/result/VirtualNodeTest.java
core/src/main/java/apoc/label/Label.java
core/src/main/java/apoc/nodes/Nodes.java
core/src/test/java/apoc/graph/GraphsTest.java

I was investigating where we use id over elementId still for a refinement card and got distracted by easy to clean up places so removed those as I went :)

[NOID] Clean up some usages of the deprecated id() and reduce warnings

---

.github/workflows/CI.yaml

`./gradlew check` has this wired, but since the checks are done per project in the CI, the global check is never run 😢, so we need to add this manually.

[VpC8nqNz] Adds license and notice validation to the CI

---

common/src/main/java/apoc/ApocConfig.java
common/src/test/java/apoc/ApocConfigTest.java
common/src/test/resources/apoc.conf

Depends on Neo4j PR for reading expandCommands.
Follows what Neo4j has:
* apoc.conf must have certain permissions only (https://neo4j.com/docs/operations-manual/current/configuration/neo4j-conf/#neo4j-conf-expand-commands)
* if the file contains a command but command expansion is not on, it will error
* if a command is invalid, it will error

[ZIv6F2QY] Allow Command Expansion APOC

---

core/src/test/java/apoc/schema/SchemasTest.java

These tests sometimes failed as the indexes weren't online yet, this awaits them and checks that fails as well

[LePmOHly] Fix flakey index test

---

core/src/test/java/apoc/export/BigGraphTest.java
core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
test-utils/src/main/java/apoc/util/TestUtil.java

.. that will be removed from Neo4j. This has hidden two errors:
* BigGraphTest registered the ImportCSV methods twice.
* TriggeredNewProcedures registered the Nodes methods twice, but also
attempted to register things on different databases (which is not
possible at the time of writing).

[NOID] Remove overrideImplementation argument

---

.github/actions/setup-jdk/action.yaml
core/src/test/java/apoc/export/ExportCoreSecurityTest.java
core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java

Cherry-picks https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3703
Checks sequences of `%e%e%f%f%e%e` do not fail but stay on the same directory when trying to do path traversals.
Commit 6616a36 reproduces the problem, the next one amends the tests to solve it.
The tests were failing in our TeamCity CI. This treats them as we were treating sequences like `..//..//`
They've solved an issue with OpenJDK where it wasn't properly detecting double slashes in a path and turning them into a single one: https://github.com/openjdk/jdk17u/commit/bc9d9c0e705cfc27f34383e68bd3b42cd8557a7b, https://nvd.nist.gov/vuln/detail/CVE-2023-22049
This fix has gone in Eclipse Temurin 17.0.8, all distributions of [Zulu](https://docs.azul.com/core/zulu-openjdk/release-notes/july-2023) or [Oracle …

[NOID] Fixes failing path traversal TeamCity tests

---

common/src/test/java/apoc/ApocConfigCommandExpansionTest.java
common/src/test/java/apoc/ApocConfigTest.java
common/src/test/resources/apoc-config-command-expansion/apoc.conf

I had seen a test failure due to the commands being seen when the apocConf was used elsewhere, so this makes sure that this test reads a special file instead.

[NOID] Fix potential ApocConfigTest issues by using a separate conf file for command expansion

---

LICENSES.txt
NOTICE.txt
common/build.gradle

Bump commons version to align the new version with the coming version of commons in core db: https://github.com/neo-technology/neo4j/pull/21746. Replaces https://github.com/neo4j/apoc/pull/472

[NOID] Bump commoms lang3 from 3.12.0 to 3.13.0

---

common/src/test/resources/spatial.json
core/src/test/java/apoc/spatial/GeocodeTest.java

The count of returned results had changed, hence them starting to break. I found the tests very hard to read so I rewrote them as well to be easier to understand.

[q5Vf4pi2] Fix broken GeoCode tests

---

LICENSES.txt
NOTICE.txt
common/build.gradle
it/src/test/java/apoc/it/core/StartupTest.java

Because the logger was colliding with the jetty one included in coredb, showing output like:
```
[main] INFO org.eclipse.jetty.server.Server - jetty-10.0.15; built: 2023-04-11T17:25:14.480Z; git: 68017dbd00236bb7e187330d7585a059610f661d; jvm 17.0.8+7
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.h.MovedContextHandler@eae9533{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.session.DefaultSessionIdManager - Session workerName=node0
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@77dae14e{/dbms,null,AVAILABLE}
```

[1F4aew1T] Uses slf4j-api 2.x api instead of slf4j-simple 1.x

---

core/src/test/java/apoc/export/cypher/ExportCypherTest.java

Things like the order in UNWIND lists and the exact ids could vary, which is not a problem for the functionality but cause flakiness of the test.
I focused on the test that was marked as flaky, but this could be done for more of the export tests as a follow-up cleanup/remove risk of flakiness task if we like to.

[uSvFQccG] Make ExportCypherTest more robust.

---

common/src/main/java/apoc/export/util/BulkImportUtil.java
common/src/main/java/apoc/export/util/MetaInformation.java
common/src/main/resources/manyTypes.csv
core/src/main/java/apoc/export/csv/CsvFormat.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java
core/src/test/java/apoc/export/csv/ExportCsvUseTypeTest.java

Added data types with config `useTypes:true`, 
consistently with [these ones](https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/#import-tool-header-format-properties)

[HJwIMwqg] apoc.export.csv.graph incorrectly exports properties with datatype float

---

LICENSES.txt
NOTICE.txt
build.gradle
core/build.gradle
readme.adoc

Bump to 5.13 and update Readme a little bit so it is sightly more useful.

[W9VglL9c] Bump APOC and Neo versions to 5.13

---

core/src/main/java/apoc/algo/PathFinding.java
core/src/main/java/apoc/coll/Coll.java
core/src/main/java/apoc/cypher/Cypher.java
core/src/main/java/apoc/cypher/CypherFunctions.java
core/src/main/java/apoc/cypher/Timeboxed.java
core/src/main/java/apoc/example/Examples.java
core/src/main/java/apoc/export/arrow/ExportArrow.java
core/src/main/java/apoc/export/csv/ExportCSV.java
core/src/main/java/apoc/export/cypher/ExportCypher.java
core/src/main/java/apoc/export/graphml/ExportGraphML.java
core/src/main/java/apoc/export/json/ExportJson.java
core/src/main/java/apoc/graph/Graphs.java
core/src/main/java/apoc/help/Help.java
core/src/main/java/apoc/index/SchemaIndex.java
core/src/main/java/apoc/lock/Lock.java
core/src/main/java/apoc/meta/Meta.java
core/src/main/java/apoc/nodes/Grouping.java
core/src/main/java/apoc/nodes/Nodes.java
core/src/main/java/apoc/path/PathExplorer.java
core/src/main/java/apoc/schema/Schemas.java
core/src/main/java/apoc/search/ParallelNodeSearch.java
core/src/main/java/apoc/stats/DegreeDistribution.java
core/src/main/java/apoc/warmup/Warmup.java

[NOID] Annotate unsafe procedures with @NotThreadSafe
When run with parallel runtime not all operations on injected instances of `Transaction` and `GraphDatabaseService` are supported. By annotating these with `@NotThreadSafe` we can avoid runtime failures and we detect already at planning that we cannot run these procedures with parallel runtime.
NOTE: the `NotThreadSafe` annotation has been merged in dev but I guess we need to wait for it to become available?

[NOID] Annotate unsafe procedures with @NotThreadSafe

---

common/src/main/java/apoc/ApocConfig.java
common/src/main/java/apoc/export/util/LimitedSizeInputStream.java
common/src/test/java/apoc/ApocConfigCommandExpansionTest.java
it/src/test/java/apoc/it/core/LoadCoreEnterpriseTest.java

Cherry picks https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3710
To allow for customers to tweak exactly how big the uncompressed files can be.

[47wOlqLp] Adds option to customize decompression ratio

---

LICENSES.txt
NOTICE.txt

Neo updated jetty, so this updates APOC license file

[NOID] Fix licenses after Neo update

---

common/src/main/java/apoc/util/kernel/MultiThreadedGlobalGraphOperations.java

Scan is deprecated, so this updates to use the new PartitionedScan

[3X06NMak] Update Scan to PartitionedScan as Scan is deprecated

---

common/src/main/java/apoc/get/Get.java
common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/algo/Cover.java
core/src/main/java/apoc/coll/Coll.java
core/src/main/java/apoc/create/Create.java
core/src/main/java/apoc/nodes/Nodes.java
core/src/main/java/apoc/path/PathExplorer.java
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/test/java/apoc/algo/CoverTest.java
core/src/test/java/apoc/create/CreateTest.java
core/src/test/java/apoc/nodes/NodesTest.java
core/src/test/java/apoc/path/ExpandPathTest.java
core/src/test/java/apoc/path/SequenceTest.java
core/src/test/java/apoc/path/SubgraphTest.java
core/src/test/java/apoc/refactor/GraphRefactoringTest.java

getId() is deprecated, so slowly clearing it out of APOC, here are some more usage removals as well as some general tidy up 🧹
Docs: https://github.com/neo4j/docs-apoc/pull/202

[Gc8EZpDO] Clean up some usages of getId() which is deprecated

---

core/src/main/java/apoc/periodic/Periodic.java

We got feedback in the APOC channel about this param being confusing, I agree so figured we can update it as it is quick to do :)
The param rate is actually a delay and not a rate (the other periodic is actually a rate)
Docs PR- https://github.com/neo4j/docs-apoc/pull/207

[NOID] Update param name to delay

---

test-utils/src/main/java/apoc/util/TestContainerUtil.java

Tmpfs has been causing flaky tests on team city.
[Green builds on TC](https://live.neo4j-build.io/buildConfiguration/CypherSurface_Apoc_Dev_BuildAndCreateArtifacts?branch=%2Fflaky-test-from-hell-mem-files&mode=builds#all-projects), historically they have 50% success rate.

[2kuFEKOe] Fix flaky integration test

---

readme.adoc

Fixes: https://github.com/neo4j/apoc/issues/514
The readme is now consistent with the APOC docs to reduce confusion :)

[NOID] Update the docker command to match the one in docs

---

core/src/main/java/apoc/export/csv/CsvFormat.java
core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java

Allow double quotes in node and rel properties with export csv.
Automatic is quote: always, so now using bulkImport everything is super quoted, but it matches how not using bulkImport works :)

[q3KTZ83O] Remove strange clean up method

---

.github/actions/gradle-command-on-pr/action.yaml
.github/workflows/ChatOps.yml
.github/workflows/spotlessApply-command.yml

Adds a job to run formatting in PRs by writting `/spotlessApply` in it
Because especially for the licensing it's really annoying to have to update neo4j locally every time the license check fails 😢 . Doing a job for the licensing from this one is super easy, this has been done in a very reusable way. Most of the code is copied from the job we have in the monorepo.

[NOID] Adds job to apply formatting in PRs

---

core/src/main/java/apoc/trigger/Trigger.java
core/src/main/java/apoc/trigger/TriggerHandler.java
core/src/main/java/apoc/trigger/TriggerInfo.java
core/src/test/java/apoc/trigger/TriggerTest.java
it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Fix a bug where active triggers are not executed.

[5kItK998] Fix bug in triggers

---

.github/actions/setup-jdk/action.yaml
.github/actions/test-gradle-project/action.yaml
.github/workflows/CI.yaml

We want to compile with JDK 17 but test with both JDK 17 and JDK 21

[NOID] Setups testing for JDK 21

---

LICENSES.txt
NOTICE.txt
common/src/main/java/apoc/convert/ConvertUtils.java
core/src/main/java/apoc/coll/Coll.java
core/src/test/java/apoc/coll/CollTest.java

Fixes arrays not being treated as lists in coll.elements as expected.

[gtjPFvMD] Fix coll support for lists coming from Nodes or Rels.

---

common/src/main/java/apoc/ApocConfig.java
common/src/main/java/apoc/load/LoadJsonUtils.java
common/src/main/java/apoc/util/FileUtils.java
common/src/main/java/apoc/util/JsonUtil.java
common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/export/csv/CsvEntityLoader.java
core/src/main/java/apoc/export/csv/ImportCsv.java
core/src/main/java/apoc/export/graphml/ExportGraphML.java
core/src/main/java/apoc/export/json/ImportJson.java
core/src/main/java/apoc/load/LoadArrow.java
core/src/main/java/apoc/load/LoadJson.java
core/src/main/java/apoc/load/Xml.java

Fixes #<Replace with the number of the issue, Mandatory>
Use Injected URLAccessChecker for checking access to URLs calling internal WebURLAccessRule directly
Proposed Changes (Mandatory)
Inject a new URLAccessChecker to separate out APOC from making internal calls into WebURLAccessRule, as this needs to changes to support RBAC permissions as well. Having this injectable will mean that we can late get this new functionality in APOC as well for free.
The alternative is to move the config only based checks into APOC.

[NOID] Use Injected UrlAccessChecker for checking access to URLs

---

common/src/main/java/apoc/ApocConfig.java
common/src/main/java/apoc/util/JsonUtil.java
core/src/main/java/apoc/spatial/Geocode.java
core/src/test/java/apoc/spatial/SpatialTest.java
it/src/test/java/apoc/it/common/UtilIT.java

More fixes for issues related to URLAccessChecker
- Geocode does these checks as well, and that was missing.
- UtilIT rewritten again to mock URLAccessChecker so as to not rely on coredb internals

[NOID] More fixes for issues related to URLAccessChecker

---

common/src/main/java/apoc/export/util/ExportConfig.java
common/src/main/java/apoc/export/util/ExportFormat.java
core/src/main/java/apoc/export/csv/ExportCSV.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java

CSV export can't use optimizations, so the check that it is correct is not very useful. In general we should probably clean up these configs as it is quite messy having all of them, but that requires an investigation into which procedure needs what 👀

[G9u7OAg9] Ignore check for optimizations if the format is CSV

---

build.gradle

Uses the [`maven-metadata`](https://repo1.maven.org/maven2/org/neo4j/neo4j-kernel/maven-metadata.xml) file to generate the versions.json instead of parsing the [`html`](https://repo1.maven.org/maven2/org/neo4j/neo4j-kernel/).
I've tried (with JVM 8) doing:
```
mkdir -p build
./gradlew versions
```
and it correctly generates a `build/versions.json` file that contains the 5.15.0 entry:
```
{
"neo4j": "5.15.0",
"neo4jVersion": "5.15.0",
"apoc": "5.15.0",
"version": "5.15.0",
"url": "https://github.com/neo4j/apoc/releases/5.15.0",
"homepageUrl": "https://github.com/neo4j/apoc/releases/5.15.0",
"jar": "https://github.com/neo4j/apoc/releases/download/5.15.0/apoc-5.15.0-core.jar",
"downloadUrl": "https://github.com/neo4j/apoc/releases/download/5.15.0/apoc-5.15.0-core.jar",
"sha1": …
```

[NOID] Adjusts versions job

---

common/src/main/java/apoc/export/util/ExportConfig.java
common/src/main/java/apoc/export/util/ExportFormat.java
core/src/main/java/apoc/cypher/CypherInitializer.java
core/src/main/java/apoc/export/csv/ExportCSV.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java
it/src/test/java/apoc/it/core/StartupTest.java
test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Some changes to help investigating a flaky test.
- Improve error handling in initializer.
- Expose neo4j logs on test container failures.
- Improve flaky test assertion.

[c11DvQNF] Investigate flaky test

---

core/src/test/java/apoc/spatial/GeocodeTest.java

- Improve assertion to investigate flaky test, instead of saying "false was not equal to true" it will report the full stack trace and error message.
- Increase timeout.

[tyXNOmR9] Investigate flaky test

---

LICENSES.txt
NOTICE.txt
common/build.gradle

I tested this manually by copying the jar to desktop and changing the name to: apoc5plus-5.15.0, without this change it fails, with it works (also with it, there is no trace of it in the logs either)

[yaWCMgIP] Exclude asm to fix startup issue

---

core/src/main/java/apoc/meta/Meta.java

Use count methods with tx state instead of ones without tx state that are deprecated and being removed.

[NOID] Use count methods with transaction state

---

core/src/main/java/apoc/export/csv/CsvEntityLoader.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java

Cherry-picks https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3898
Uses `RFC4180Parser` instead of `CSVParser` as suggested [here](https://stackoverflow.com/questions/46139735/why-csvwriter-and-csvreader-uses-different-default-escape-characters)
Because the case where we have a quote `"` in a value we want to export / import from csv was not working:
```
CREATE (n:Test {name: 'Test', value: '{"new":"4\'10\\\""}'});
CALL apoc.export.csv.all("test.csv", {bulkImport:'true'});
MATCH (n) DETACH DELETE n;
CALL apoc.import.csv([{fileName: 'file:test.nodes.Test.csv', labels: ['Test']}],[],{});
```
```
MATCH (n: Test) RETURN n.value
```
should give us a roundtrip where the result is `"{"new":"4'10\""}"`

[SGrPWNEf] Fixes backslashes parsing in csv import / export

---

common/src/main/java/apoc/load/Mapping.java

Adds a default value to a method in common which could throw a null pointer when used from APOC extended.
The null pointer could only occur when used from apoc.load.csv and not apoc.import.csv, so it was not possibly to write a test in core for this.

[mMXNEtoY] Add default value for optionalData.

---

LICENSES.txt
NOTICE.txt
it/src/test/java/apoc/it/core/CypherEnterpriseTest.java
it/src/test/java/apoc/it/core/ExportCsvIT.java
it/src/test/java/apoc/it/core/GraphRefactoringEnterpriseTest.java
it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
test-utils/build.gradle
test-utils/src/main/java/apoc/cypher/CypherTestUtil.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Updates the java-driver dependency used in the ITs to the latest currently (from `4.4.12` -> `5.16.0`).
There have been some [additional checks](https://neo4j.com/docs/java-manual/current/session-api/#java-driver-simple-result-consume) added in the 5.x series of the driver. This PR also migrates some usages of the driver from the deprecated `writeTransaction()` to `executeWrite()`.

[NOID] Upgrade driver used in tests to 5.16.0

---

core/src/test/java/apoc/export/ExportCoreSecurityTest.java

Changes the name of the directory `apoc` to `"__non-existing-dir__"` so we get more chances of that directory truly not existing.
Because in some internal build we have an existing `apoc` folder which was making the tests not work because they expect that folder to not exist.

[NOID] Fixes directory that should be non existing

---

core/src/main/java/apoc/cypher/Cypher.java
core/src/test/java/apoc/cypher/CypherTest.java
it/src/test/java/apoc/it/core/CypherEnterpriseTest.java
test-utils/src/main/java/apoc/cypher/CypherTestUtil.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Fixes two issues in `apoc.cypher.runMany`:
- Transactions were accessed from multiple threads, this is not allowed and has undefined behavior (this has always been the case but recently this has started to cause more problems like flaky tests, probably some change in kernel that makes it more sensitive).
- Errors silently stopped the procedure from processing. This was not documented so I assume it was an oversight.
For simplicity, the implementation is changed to be single threaded. We previously spawned a second thread for executing inner queries. While this could have performance benefits in some situations, there is also an overhead of starting and synchronizing threads. We currently have no benchmarks for this procedure so there's not much to base this decision on either way.
Some …

[f3ZUxEG2] Fix bugs and refactor apoc.cypher.runMany

---

core/src/main/java/apoc/meta/Meta.java
core/src/main/java/apoc/util/Utils.java
core/src/test/java/apoc/util/UtilsTest.java

The hash functions are only intended for strings, but unfortunately their signature allows all types. This is a safety for users that use hash functions on non string values despite the documentation.

[h7Q1epCi] Make hashing functions stable on all neo4j types

---

core/src/main/java/apoc/meta/Meta.java
core/src/test/java/apoc/meta/MetaTest.java

Solves #583 
Because a node named `NODE` or a relationship named `RELATIONSHIP` could not be used.
When doing
```
CREATE (a:NODE)-[r:RELATIONSHIP]->(m:Movie)
CALL apoc.meta.data()
```
we were getting:
```
java.lang.IllegalArgumentException: duplicate element: RELATIONSHIP
```

[wbVWvi0y] Solves apoc.meta.data bug with reserved names for relationships and nodes

---

common/src/main/java/apoc/ApocConfig.java
common/src/test/java/apoc/ApocConfigCommandExpansionTest.java
common/src/test/java/apoc/ApocConfigTest.java

On Windows service, 'sun.java.command' is not supported. The fallback default path to the config folder was set to '.' which is not the actual default. With this solution, the home folder of Neo4j is instead used to calculate the default.
In order to get it to work when both APOC Core and Extended is installed, I reckon the same change should also be applied to [extended/src/main/java/apoc/ExtendedApocConfig.java](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extended/src/main/java/apoc/ExtendedApocConfig.java)

[4Bece3wd] Use Neo4j home to determine default config location.

---

LICENSES.txt
NOTICE.txt
common/build.gradle
core/src/main/java/apoc/coll/Coll.java
core/src/main/java/apoc/coll/Combinations.java
core/src/main/java/apoc/coll/StandardDeviation.java
core/src/main/java/apoc/math/Regression.java
core/src/main/java/apoc/math/SimpleRegression.java
core/src/test/java/apoc/math/RegressionTest.java

We only used a few methods from the library. Also, the `FastMath` that the library is built on claims to be faster and more accurate, but this is a lie in modern versions of Java. Performance will actually be worse since no intrinsics will be used.

[NOID] Remove commons math3

---

core/src/main/java/apoc/cypher/Cypher.java

Add `@NotThreadSafe` to `apoc.do` and `apoc.when`

[NOID] Annotate apoc.do with @NotThreadSafe

---

common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/test/java/apoc/refactor/GraphRefactoringTest.java

There was a github issue where a user complained that if the Cypher query failed after this procedure ran, the procedure itself still committed the result. This is because it opened new transactions inside, this seemed overkill, so removed that from happening.

[oIVz2Y7V] apoc.refactor.cloneNodes does not need to be in its own transaction

---

it/src/test/java/apoc/it/core/RBACOnLoadTest.java

Add tests for all loading procedures in APAC to check the deny works well with RBAC rules.
docs: https://github.com/neo4j/docs-apoc/pull/260

[RHMU1hOu] Add tests for RBAC deny on load

---

common/src/main/java/apoc/util/Util.java
core/src/test/java/apoc/periodic/PeriodicTest.java

For maps which in turn contain maps or lists, we would call Collectors.toUnmodifiableMap, which throws a null pointer if the map also contains null values. This should be valid in Cypher.
Inspiration for the fix comes from https://stackoverflow.com/questions/24630963/nullpointerexception-in-collectors-tomap-with-null-entry-values

[z9rBzmVK] Make recursiveRebind nullsafe for maps.

---

.github/workflows/CI.yaml
LICENSES.txt
NOTICE.txt
core/src/main/java/apoc/convert/Json.java
core/src/main/java/apoc/periodic/Periodic.java
core/src/test/java/apoc/convert/PathsToJsonTreeTest.java
it/src/test/java/apoc/it/core/ApocSplitTest.java
it/src/test/java/apoc/it/core/PeriodicIterateTest.java
test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java

Cherry picked from https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4044
Adds a new method `convert.paths.toTree` that deprecates `convert.toTree`.
Closes #3996, #3997
There were several problems with the old method. For paths:
```
v1 -> v2 -> v3
v2 -> v2 //self-loop
```
it was outputting:
```
v1 -> v2 -> v2
v2 -> v2
```
instead of:
```
v1 -> v2 -> v2
-> v3
```
This PR adds a new method that:
* Fixes the behaviour for cyclic paths.
* Fixes the behaviour for bidirectional paths.
* Fixes the properties filter for both of the method when the nodes have several labels.

[pb3CtuNX] Adds convert.paths.toTree to deprecate old convert.toTree

---

core/src/main/java/apoc/export/csv/CsvEntityLoader.java
core/src/main/java/apoc/export/csv/ImportCsv.java
core/src/main/java/apoc/export/graphml/ExportGraphML.java
core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java

Reports that the file is being reported as in use after the procedure has been used.

[NOID] Close resources for open readers

---

core/src/main/java/apoc/export/cypher/ExportCypher.java
core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java

If stream is forced then a user must have their config set to allow export, even when filename is null which is that the user wants to stream those results. This was not streaming because the reporter never considered itself "done" so set done after schema values are collected.

[WVuGDROz] Allow cypher.export.schema return using a stream

---

test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java

HTTP wait strategy fails in certain builds when browser is not bundled.

[NOID] Update wait strategy

---

core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java

If a relationship in a graphml file are defined before the nodes they reference, a null error is thrown which is not very descriptive. So this updates it to make it clearer.
Note, I looked into holding off and continuing with the nodes and coming back to the missed relationship, but it gets complicated because the file is read line by line and the properties etc are part of this. But let me know if you think we should be doing that approach instead. It is doable, but I am not sure of the use case (as this is the first issue finding this).

[3yfKdDEx] Give a clear error message when a relationship is defined before its node

---

common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/CoreApocGlobalComponents.java
core/src/main/java/apoc/trigger/Trigger.java
core/src/main/java/apoc/trigger/TriggerHandler.java
core/src/test/java/apoc/trigger/TriggerDisabledTest.java
core/src/test/java/apoc/trigger/TriggerRestartTest.java
core/src/test/java/apoc/trigger/TriggerTest.java
core/src/test/java/apoc/util/UtilTest.java

Some of the TriggerHandler code, in particular the start() method was run even if triggers were disabled. This could cause issues in some edge cases as well as impact performance.
Also improve testing of disabled triggers.

[hxmGFWvF] Only create a TriggerHandler if triggers are enabled.

---

core/src/test/java/apoc/util/LogsUtilTest.java

Because \u0085 is being removed, to help users keep consistent queries, this is quoted in 5 (and in 6), was a minor change that I wasn't expecting APOC to be testing of all places 😆

[NOID] Fix broken APOC test

---

build.gradle
core/src/main/java/apoc/text/Strings.java
core/src/test/java/apoc/text/StringsTest.java
it/src/test/java/apoc/it/core/ApocSplitTest.java

Added a new function for a support case surrounding the ability to reference group names.
Docs: https://github.com/neo4j/docs-apoc/pull/312

[7hH8ZRTU] Add new regex matcher by group names

---

test-utils/src/main/java/apoc/util/TestContainerUtil.java

Fixes apoc tests after `internal.dbms.type_constraints` was removed in https://github.com/neo-technology/neo4j/pull/24597.

[NOID] Remove obsolete configuration

---

core/src/main/java/apoc/export/csv/CsvFormat.java
core/src/main/java/apoc/export/csv/ExportCSV.java
core/src/main/java/apoc/export/cypher/ExportCypher.java
core/src/main/java/apoc/export/graphml/ExportGraphML.java
core/src/main/java/apoc/export/json/ExportJson.java
core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java
core/src/test/resources/procedures.json

When bulkImport was set to true, the quoting option the user input no longer worked. This PR makes the quoting work again and makes sure the defaults align with how it works for streaming and when bulkImport is false.

[d4rLFQqM] Align all export modes with quoting consistency

---

common/src/main/java/apoc/load/Mapping.java
common/src/main/java/apoc/meta/Types.java
core/src/test/java/apoc/export/csv/ImportCsvTest.java

Long and Double types can be exported but not imported, so this PR allows for them to be imported (if CSV header says prop:long or prop:double for example).
This PR builds on top of https://github.com/neo4j/apoc/pull/665

[yVM4sJbH]  Dev fix round trip for csv loading

---

core/src/test/java/apoc/periodic/PeriodicTest.java
test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java

Fixes #<Replace with the number of the issue, Mandatory>
One sentence summary of the change.
A brief list of proposed changes in order to fix the issue:
-
-
-

[aWY2zoX5] Replaced testTerminatePeriodicQuery with testTerminateWithCommand

---

common/build.gradle
core/build.gradle
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/test/java/apoc/refactor/CloneSubgraphTest.java
core/src/test/java/apoc/refactor/GraphRefactoringTest.java
core/src/test/resources/procedures.json
processor/build.gradle

Add option `createNodesInNewTransactions` to `apoc.refactor.cloneSubgraph` that let's you control if nodes are created in inner transactions. Previous behavior was to create each node in a new transaction (relationships were not though, surprisingly). New default behavior is to use the outer transaction for all writes (`createNodesInNewTransactions = true` gives the old behavior still).

[bkym7TcZ] Optimise apoc.refactor.cloneSubgraph

---

common/src/main/java/apoc/export/util/ExportUtils.java
common/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
common/src/main/java/org/neo4j/cypher/export/ExportData.java
core/src/main/java/apoc/export/csv/CsvFormat.java
core/src/main/java/apoc/export/csv/ExportCSV.java
core/src/main/java/apoc/export/graphml/ExportGraphML.java
core/src/main/java/apoc/export/json/ExportJson.java

Fix unsafe use of transactions in export csv.

[Carz4Ljs] Safe use of transactions in export csv

---

core/src/main/java/apoc/cypher/CypherInitializer.java

- Add better logging when apoc fails to cleanup triggers during database drop.
- Ignore trigger cleanup when system db is unavailable.

[EUtjTRHb] Better error handling and logging during cleanup of triggers

---

core/src/main/java/apoc/help/Help.java
core/src/main/java/apoc/schema/Schemas.java
core/src/test/java/apoc/schema/SchemasTest.java
it/src/test/java/apoc/it/core/StartupTest.java
processor/src/main/java/apoc/processor/ApocProcessor.java
processor/src/main/java/apoc/processor/ExtensionClassWriter.java
processor/src/main/java/apoc/processor/SignatureVisitor.java
processor/src/test/java/apoc/processor/ApocProcessorTest.java
processor/src/test/java/apoc/processor/ProcedureSignatureVisitorTest.java
processor/src/test/java/apoc/processor/UserAggregationFunctionSignatureVisitorTest.java
processor/src/test/java/apoc/processor/UserFunctionSignatureVisitorTest.java

The name column was different between these 2 equivalent procedures, and wasn't even actually giving the name of the constraint/index. So this makes it more consistent with SHOW CONSTRAINTS/INDEXES

[3Hl7fTsQ]  Dev fix misleading name column

---

readme.adoc

The README shows `name : : TYPE` with an irritating space in between.
Get rid of the space and make the README show `name :: TYPE`.

[NOID] show the :: without an irritating space in between

---

common/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
common/src/test/resources/init_neo4j_export_csv.cypher
core/src/test/java/apoc/export/cypher/ExportCypherTest.java
it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java

- Increased `apoc.export.cypher.data/graph` test coverage with indexes and constraints
- Added schema relationship support to `apoc.export.cypher.data/graph` procedures

[d0LvEgnK] Check the correct behaviour with indexes/constraint using the apoc.export.cypher.data/graph procedures

---

core/src/main/java/apoc/load/LoadJson.java
core/src/test/resources/procedures.json

To align with https://github.com/neo4j/docs-apoc/pull/345 
This fixes the description, which was wrong.
It mentions url encoding as a reaction to https://github.com/neo4j/apoc/issues/65

Update description of apoc.load.jsonParams

---

core/src/main/java/apoc/path/PathExplorer.java
core/src/test/java/apoc/path/ExpandPathTest.java

If a user types in the an invalid uniqueness value, they wouldn't know, so this will now error; https://github.com/neo4j/apoc/issues/85

Error on typos for uniqueness

---

common/src/main/java/apoc/export/util/MetaInformation.java
core/src/main/java/apoc/export/csv/CsvFormat.java
core/src/test/java/apoc/export/csv/ExportCsvTest.java

Fixes https://github.com/neo4j/apoc/issues/105

Add float type and fix values not showing with useTypes is used

---

common/src/main/java/apoc/ApocExtensionFactory.java

Allow loading of service listeners in a way that doesn't require the storing of the class separately, see the corresponding PR on APOC Extended https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4278

Update to behave differently for APOC extended

---

common/src/main/java/apoc/result/VirtualNode.java
core/src/main/java/apoc/create/Create.java
core/src/test/java/apoc/create/CreateTest.java
core/src/test/resources/functions/common/functions.json

Apparently the original idea of this function was to just wrap real nodes aka keep their ids, to not break any existing behaviour I have added that as a config option instead
docs: https://github.com/neo4j/docs-apoc/pull/363

Add option to wrap a nodes id to the apoc.create.virtual.fromNode

---

common/src/main/java/apoc/ApocExtensionFactory.java
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/test/java/apoc/refactor/CloneSubgraphTest.java

Cherry-pick of [cloneSubgraph fix](https://github.com/neo4j/apoc/pull/715) to 5.26 LTS.

5.26 LTS clone subgraph properties fix

---

build.gradle
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/test/java/apoc/refactor/CloneSubgraphTest.java

Fixes bug introduced in [PR](https://github.com/neo4j/apoc/pull/674) were properties on relationships are lost when using `cloneSubgraph`.

Fixed issue with properties in CloneSubgraph

---

core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/test/java/apoc/ArgumentDescriptionsTest.java
core/src/test/java/apoc/refactor/GraphRefactoringTest.java
core/src/test/resources/procedures/common/procedures.json

Fixes #699
- Better handling of constraints in `apoc.refactor.to`, `apoc.refactor.from`, `apoc.refactor.invert` and `apoc.refactor.mergeNodes`.
- Add option to fail on errors in `apoc.refactor.to`, `apoc.refactor.from` and `apoc.refactor.invert`.

Fix handling of constraints in refactor procedures

---

core/src/main/java/apoc/cypher/Timeboxed.java
core/src/test/java/apoc/cypher/CypherTest.java
core/src/test/resources/procedures/common/procedures.json
core/src/test/resources/procedures/cypher25/procedures.json
core/src/test/resources/procedures/cypher5/procedures.json

The timeout procedure is a bit weird, we had a user request to give status codes. I have updated it so that there are 2 options, one which fails on error, and one which returns an extra row at the end, which is the status :) 
https://github.com/neo4j/docs-apoc/pull/362

Add failOnError and return status options to apoc.cypher.timeboxed

---

common/src/main/java/apoc/util/Util.java
core/src/test/java/apoc/ArgumentDescriptionsTest.java
core/src/test/java/apoc/convert/ConvertJsonTest.java
core/src/test/java/apoc/convert/PathsToJsonTreeTest.java
core/src/test/java/apoc/cypher/CypherTest.java
core/src/test/java/apoc/export/ImportAndLoadCoreSecurityTest.java
core/src/test/java/apoc/export/SecurityTestUtil.java
core/src/test/java/apoc/export/arrow/ArrowTest.java
core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
core/src/test/java/apoc/help/HelpTest.java
core/src/test/java/apoc/load/LoadJsonTest.java
core/src/test/java/apoc/map/MapsTest.java
core/src/test/java/apoc/meta/MetaTest.java
core/src/test/java/apoc/schema/SchemasTest.java
core/src/test/java/apoc/text/StringsTest.java
core/src/test/java/apoc/trigger/TriggerDisabledTest.java
core/src/test/java/apoc/trigger/TriggerTest.java
core/src/test/java/apoc/warmup/WarmupTest.java
it/src/test/java/apoc/it/core/ApocVersionsTest.java
test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java

Add config and env variable to be able to test Cypher Versions - ready to fix all Cypher 25 test failures

Add ability to test different cypher versions globally

---

common/src/main/java/apoc/util/Util.java
it/src/test/java/apoc/it/core/ApocSplitTest.java
it/src/test/java/apoc/it/core/RBACOnLoadTest.java
it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
it/src/test/java/apoc/it/core/TriggerClusterRoutingTest.java
it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
it/src/test/java/apoc/it/core/WarmupEnterpriseTest.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Add ability to change Cypher version in Docker Tests

Dev test cypher versions docker

---

core/src/main/java/apoc/nodes/Grouping.java
core/src/test/java/apoc/nodes/GroupingTest.java

https://github.com/neo4j/apoc/issues/116

Add other types to give a more robust grouping proc

---

common/src/main/java/apoc/export/util/LimitedSizeInputStream.java

Fixes "graphml import query is locking the graphml file after execution"
`LimitedSizeInputStream` misses a close method causing file handles on imports to remain open (until collected by GC).
This PR adds the missing close method, which fixes the problem.

Add close() method to `LimitedSizeInputStream`

---

common/src/main/java/apoc/util/LogsUtil.java
common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/cypher/CypherInitializer.java
core/src/test/java/apoc/export/arrow/ArrowTest.java
core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
core/src/test/java/apoc/trigger/TriggerDisabledTest.java
core/src/test/java/apoc/trigger/TriggerTest.java
core/src/test/java/apoc/util/LogsUtilTest.java
core/src/test/java/apoc/warmup/WarmupTest.java
it/src/test/java/apoc/it/core/WarmupEnterpriseTest.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java
test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java

Depends on https://github.com/neo-technology/neo4j/pull/29336

Adapt to new preparser API

---

core/src/test/java/apoc/periodic/PeriodicTest.java

This test was running continuously 1000 creates, using a MERGE instead it hopefully won't run out of memory as often

testTerminateCommit: stop test going out of memory

---

common/src/main/java/apoc/result/VirtualNode.java
core/src/test/java/apoc/create/CreateTest.java

Fixes https://github.com/neo4j/apoc/issues/721.
If it isn't specified that the virtual node should keep the original id, the new virtual nodes will get new negative ids (unique)

Fix virtual node id working

---

common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
core/src/test/java/apoc/meta/MetaTest.java

A non-existing label or type has the id of -1, which so happens to be the id of the constant for "ANY_LABEL" and "ANY_TYPE" which meant giving non-existing ones in would return the count of the db 😅
Fixes: https://github.com/neo4j/apoc/issues/68

Fix apoc.meta.subgraph for non-existing labels and types

---

common/src/main/java/apoc/result/VirtualNode.java
common/src/main/java/apoc/result/VirtualRelationship.java
common/src/test/java/apoc/result/VirtualNodeTest.java
core/src/main/java/apoc/trigger/TriggerMetadata.java
core/src/test/java/apoc/graph/GraphsTest.java
core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java

When accessing a deleted relationship or node from a trigger, rel start and end node references still held onto the hold tx which caused errors and neither contained real ids and element ids which is unexpected behaviour

Set up more robust virtual entities for deleted nodes and relationships

---

core/src/test/java/apoc/util/UtilsTest.java

Exclude vector from tests (I will create a card for myself to revert when this is fixed on neos side)

Filter out vector types as they aren't currently storable

---

build.gradle
it/build.gradle
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Make `:it:test` depend on `:core:shadowJar` and copy the apoc jar from the build instead of trying to invoke gradle programatically from the test code. Attempt to fix issue with the build where the wrong version of apoc is used in docker based tests.

Fix integration tests

---

common/src/main/java/apoc/ApocConfig.java

A bunch of tests started failing due to an update in Neo to do with the naming of import folders for tests, this fixes it

Update test folder to match Neo's new naming

---

common/src/main/java/apoc/result/VirtualNode.java
common/src/main/java/apoc/result/VirtualRelationship.java

NOTE: I put it in to keep track of it, but probably, to make the CI work, a PR should be done by pushing against upstream, instead of my fork ?
Because I don't have access at the moment, unfortunately :(
---
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/4378
In APOC Extended there are some procedures that use VirtualNode Sets (i.e. some of the  `apoc.nlp.*`) e.g. [at this point](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extended/src/main/kotlin/apoc/nlp/aws/AWSVirtualSentimentVirtualGraph.kt#L18).
However, via [this change](https://github.com/neo4j/apoc/commit/51d13ee49980def7557c6ac4a987843439825a92#diff-144887c5edacf927d08fe68a4e09e316e793b867034fecc7190897805e6d94f4R69-R70), 
they currently no longer work (e.g.[ …

Fix virtual entities hashCode

---

core/src/main/java/apoc/util/Utils.java
core/src/test/java/apoc/util/UtilsTest.java

Allow null values as implied by the documentation.

Allow null values for apoc.util.validatePredicate

---

common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
core/src/test/java/apoc/export/cypher/ExportCypherTest.java

Fixes https://github.com/neo4j/apoc/issues/769 by making sure that if a unique constraint is used, then the node has all the required unique properties

Fix issue with export with constraints

---

common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
core/src/main/java/apoc/export/cypher/ExportCypher.java
core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
core/src/test/java/apoc/export/cypher/ExportCypherTest.java

Fix unsafe use of transactions. Attempt to fix:
- https://trello.com/c/gRSYmlRs/2615-nightly-test-failure-apocexportcypherexportcyphermultireltestcreateoptimizationnone-is-failing-in-a-pipeline-run
- https://trello.com/c/Il7Rm3eN/2605-nightly-test-failure-apocexportcypherexportcyphermultireltestaddstructurewithoptimization-is-failing-in-a-pipeline-run
- https://trello.com/c/OwcxoHDR/2612-merge-test-failure-apocexportcypherexportcyphermultireltestupdatestructurewithoptimization-is-failing-in-a-pipeline-run
- https://trello.com/c/XpmvYy8q/2613-merge-test-failure-apocexportcypherexportcyphermultireltestcreatewithoptimization-is-failing-in-a-pipeline-run
- https://trello.com/c/uHttAONj/2614-merge-test-failure-apocrefactorgraphrefactoringtestshouldalwaysoverridenodepropsifnotsetandcombinerelpro …

Fix unsafe use of transactions in Cypher export

---

common/src/main/java/apoc/periodic/PeriodicUtils.java
common/src/main/java/apoc/util/Util.java
core/src/main/java/apoc/periodic/Periodic.java
core/src/test/java/apoc/periodic/PeriodicTest.java
test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java

https://trello.com/c/Vi3h8rVw/2396-we-should-not-allow-concurrent-execution-of-apocperiodicrepeat

Make periodic procedures safe to call concurrently

---

common/src/main/java/apoc/util/Util.java
core/src/test/java/apoc/export/json/ImportJsonTest.java
core/src/test/resources/exportJSON/importPointValues.json
core/src/test/resources/exportJSON/invalidPointValues.json

A user found an issue that the POINT value fails if the CRS is not specified, but as Neo has set rules for determining the CRS, this doesn't make much sense. I added an inference step if no CRS is supplied, and a better error message if it can't be figured out.

Add POINT value inference

---

core/src/main/java/apoc/agg/Graph.java
core/src/main/java/apoc/agg/Product.java
core/src/main/java/apoc/algo/Cover.java
core/src/main/java/apoc/coll/Coll.java
core/src/main/java/apoc/convert/Convert.java
core/src/main/java/apoc/create/Create.java
core/src/main/java/apoc/date/Date.java
core/src/main/java/apoc/meta/Meta.java
core/src/main/java/apoc/nodes/Nodes.java
core/src/main/java/apoc/refactor/GraphRefactoring.java
core/src/main/java/apoc/refactor/rename/Rename.java
core/src/test/resources/functions/common/functions.json
core/src/test/resources/functions/cypher25/functions.json
core/src/test/resources/functions/cypher5/functions.json
core/src/test/resources/procedures/common/procedures.json
core/src/test/resources/procedures/cypher25/procedures.json
core/src/test/resources/procedures/cypher5/procedures.json

Based on the benchmarking analysis, these are the procedures and functions that I deemed were easy to do in Cypher as well as showed a better performance in Cypher.
See [here](https://github.com/neo4j/docs-apoc/pull/439) for the docs

Deprecate procedures and functions that are easy to do in Cypher and are more performant in Cypher as well.

---

core/src/main/java/apoc/cypher/CypherInitializer.java
it/src/test/java/apoc/it/core/StartupTest.java
test-utils/src/main/java/apoc/util/TestContainerUtil.java

Use the unsupported backup way of checking in case the kernel version has been overridden.

Fix incompatible warning on startup with 5.27

---

core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java

Fixes: https://github.com/neo4j/apoc/issues/444
Gives support for import Graphml with NAN values for number types. Int and Long in Java do not support NaN, so it will be a Float.NaN in this case, the only potential issue is if a user has a constraint on what they are importing for having it as an INTEGER, but I believe this is a better issue than the import just failing with an exception.

Add NAN support to graphml imports

---

core/src/test/java/apoc/test/util/RandomGraph.java

Fixes broken reference to `org.neo4j.values.storable.ValueType` enum constants.

fix broken references

---

it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java
it/src/test/java/apoc/it/core/ImportJsonEnterpriseFeaturesTest.java
it/src/test/java/apoc/it/core/MetaEnterpriseFeaturesTest.java
it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java

The main objective is to stop using deprecated methods that have been removed in the next major driver version.

Migrate from deprecated neo4j-java-driver methods to new ones

---

core/src/test/java/apoc/schema/SchemasTest.java

`FULLTEXT` index descriptor strings now reflect the disjunction of multiple entry tokens.
Rather than: `(:Label1:Label2:Label3 {prop1, prop2, prop3})`  
It should be: `(:Label1|Label2|Label3 {prop1, prop2, prop3})`

Update schema descriptor for disjunction of entity tokens for fulltext
